### ISSUE TITLE
Filter out lbry app frontpage requests from trending spee.ch images 

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#103]
As a spee.ch user, I want to see which images are trending within the spee.ch community without it being clouded by images being frequently requested by other apps, so that I can see fun images and partake in trending image challenges.

**Comment by kauffj** [comment]
https://api.lbry.io/discover/list?version=early-access gives the list of content on the homepage.

**Comment by billbitt** [comment]
I found that using the API would work for filtering out images and videos that are themselves on the homepage, but I can't identify details about the thumbnail (beyond it's url) and thumbnails are a big part of what we would want to filter out.  I think it may be best to not worry about it for now and trust that good publishes through spee.ch being shared on reddit, facebook, etc will have the numbers to rise above the app thumbnails in the trending area.  A more robust trending algorithm which can pay attention to more factors that just total views over time will likely be needed soon enough anyways.

**Comment by billbitt** [comment]
I did manually filter out some of the top thumbnails by switching them to 'nsfw' in the spee.ch file database.  It does not affect the claim's metadata in lbry, just a quick patch to filter out some images from the homepage trending area.

**Comment by kauffj** [comment]
Booo for the nsfw hack. Add a column!

**Comment by billbitt** [comment]
haha, will do.

**Comment by billbitt** [comment]
added `trendingEligible` column with default of `true`
