### ISSUE TITLE
Add open graph meta tags (used by Facebook)

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#109]
See [here](http://ogp.me/). We'd definitely want the main four. You can also look at what lbry.io or other sites do.

**Comment by billbitt** [comment]
for twitter:
- need Player Cards to support unfurling of videos in twitter
- need to add meta tags to serve routes to images unfurl in twitter

**Comment by billbitt** [comment]
for videos, need to generate thumbnail with it

**Comment by billbitt** [comment]
this is almost done, but before the twitter card will play video, I have to submit for white listing.

**Comment by billbitt** [comment]
requested twitter whitelist for video player card

**Comment by billbitt** [comment]
spee.ch was whitelisted.  

- need to verify cards are displaying properly across devices
- should limit meta tags to sfw to comply with twitter requirements

**Comment by billbitt** [comment]
future improvements:
- set meta height and width dynamically based on the provided content
- thumnails 
- click through should be direct to show lite page?
