### ISSUE TITLE
height undefined error when resolving claim for first time on speech

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#112]
I uploaded lbry://lbrylogo2 and when I went to https://spee.ch/lbrylogo2, I got an error about height being undefined with a white background, plain black text. 

After clicking refresh, the page loaded correctly. 

Per @billbitt , this only happens on claims the first time they are loaded through spee.ch

**Comment by billbitt** [comment]
![error](https://i.imgur.com/NIzlnII.jpg)

**Comment by billbitt** [comment]
I tried to reproduce and was unsuccessful.  I do believe this is still happening though, so I am going to leave this issue open.

**Comment by billbitt** [comment]
I believe this is fixed with the changes to use MySQL for resolving claims
