### ISSUE TITLE
wrong image is returned to user

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#126]
Issue:  A user will publish an image through spee.ch, but when they check the url, a different image is served to them.

**Comment by MSFTserver** [comment]
ok so i can display the correct image if i void out the /media and use the href link with .png at the end
would this be an option or is the /media needed for something?

**Comment by MSFTserver** [comment]
example:
go here https://spee.ch/423dac99270f7f17675d1114f5b80cc191e4e46a/non-closing.png
open developer tools -> copy href link -> paste link into `img` class with .png at end
Gif of process: 
https://spee.ch/e/display-correct-image.gif

**Comment by tzarebczan** [comment]
Here's another one I just uploaded: https://spee.ch/b48717470b62676fc4e1ecc1f1bad66427d0a137/genwyn1 which shows some bitcoin download image

It should be showing this foxy lady: https://spee.ch/@randomnsfw:ce99ee6b2ad23a0d8a3fc66d017ab599d8be1b4d

Maybe something to do with the filename? It was download.jpg

**Comment by MSFTserver** [comment]
@tzarebczan yes that the filename issue it servers `<img class="image-show" src="/media/download.jpg">` from media and it should be`<img class="image-show" src="/b48717470b62676fc4e1ecc1f1bad66427d0a137/genwyn1.jpg"> `

we should serve the href link above in the a tag

**Comment by MSFTserver** [comment]
atleast thats quick fix i found

**Comment by MSFTserver** [comment]
not sure why even use the media folder for serving id think wed just need that for lbry end

**Comment by billbitt** [comment]
closing.  fixed in current working branch redesign-1.  thanks guys.
