### ISSUE TITLE
Albums / Collections

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#128]
As a user, sometimes I have multiple related images I want to share under one URL.

**Comment by billbitt** [comment]
I am going to move this to Icebox since it is potentially a new feature and not a fix to the existing functionality.  What do we want to add here, or is this a change/update to channels?

**Comment by kauffj** [comment]
This is not very important with the addition of channels.

**Comment by skhameneh** [comment]
Now that we have channels, we can likely close this unless we want to revisit a concept of collections managed by a DB on Spee.ch.  Likely we can close this; marking `icebox` for now.
