### ISSUE TITLE
New design of spee.ch

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#131]

**Comment by MSFTserver** [comment]
this still needed? i could start working on nicer theme

**Comment by kauffj** [comment]
We have someone pursuing this who's work we trust, but anyone is welcome to PR. The chrome plugin might be a good one?

**Comment by MSFTserver** [comment]
that all i was wondering saw no comments on it just making sure but yea i was looking into some plugin for other apps to upload pictures see if i cant work off those

**Comment by billbitt** [comment]
closing this general issue.  we can create specific issues for outstanding design bugs/enhancements
