### ISSUE TITLE
urls with only a claim name should be shareable on social media

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#139]
story: As a user, I want to be able to share `spee.ch/example` and have my favorite social media treat it like a long url, so that I can share content easily with my friends.

notes:
Open graph and twitter are throwing an errors for these links.  I believe spee.ch is sending the asset by itself and not the html show/show-light route.

**Comment by MSFTserver** [comment]
you try add head tags like this?
```
<meta name="twitter:site" content="@LBRYio">
<meta name="twitter:domain" content="spee.ch">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{fileInfo.name}}">
<meta name="twitter:description" content="Spee.ch: Decentralized Image Hosting using Lbry Protocol">
<meta name="twitter:image:src" content="https://spee.ch/{{fileInfo.claimId}}/{{fileInfo.name}}.{{fileInfo.fileExt}})">
<meta name="twitter:image:height" content="630">
<meta name="twitter:image:width" content="1200">
```

**Comment by MSFTserver** [comment]
https://github.com/lbryio/spee.ch/pull/158/commits/d2c4ce8b923cdccc2b94cb7e019693f9daee3209
