### ISSUE TITLE
Permanent short link is missing claim id 

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#142]
See: https://spee.ch/lbrydropgif

The short link is currently showing as https://spee.ch//lbrydropgif.gif (two slashes, no claim id)

**Comment by billbitt** [comment]
Same issue here:
https://spee.ch/df125098df7ee6ccb33726dd04f89e158e8f7129/th 
![pasted image at 2017_08_08 03_07 am](https://user-images.githubusercontent.com/19243959/29076274-eaa66572-7c09-11e7-9cc1-a771fe8a1f69.png)
