### ISSUE TITLE
some videos published via the app are not served by speech properly

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#145]
As a user, I want to be able to use speech to distribute my videos, that I uploaded through the app, to non app users via spee.ch urls.

@fcbrandon in slack reported that a video he uploaded via the app is not being displayed properly on spee.ch.  
The url is https://spee.ch/a70296a73e14280616d221a097bdc0b440ccc4c2/winmrportalrecording-nativeres-unnarrated-fcbrandon.mp4

I also uploaded the video via the app and tried to access with no success.  spee.ch url below:
spee.ch/0475b7c3966569b0a98e69261468bb20b2af6962/winmrportalwonarration

I have not been able to identify why yet.  It is mp4 and works in the app.  The only thing out of the oridinary that I see is it is over 200mb, but I am not sure that it is related to length.

**Comment by fcbrandon** [comment]
Note, I tried to publish a different video, which was under 100MB (approx. 90MB) and ran into a similar problem - the new content doesn't play from spee.ch either.

**Comment by seanking2919** [comment]
I actually have these problems with Sandia Mesa's videos uploaded via the LBRY app too. So, you're not the only one, @fcbrandon.

**Comment by billbitt** [comment]
https://spee.ch/7fcc8c6455632fbffde3843df0c7039a2b4646bd/thesolarsystemexplained

**Comment by seanking2919** [comment]
Nice @billbitt. Glad to see you're making progress with it.

**Comment by seanking2919** [comment]
However, I did notice that whenever you clicked anywhere on the video player, it would immediately go to either the page of just the video or back to the spee.ch page. :/

**Comment by MSFTserver** [comment]
![image](https://user-images.githubusercontent.com/18357967/29992256-111ee63e-8f4c-11e7-9e24-e4af4f0cf8fc.png)
maybe it has something to do with the way it handles spaces...noticed alot of data inst sent with the broken vids

**Comment by seanking2919** [comment]
@MSFTserver I'm wondering if that's the exact issue with my videos:
https://spee.ch/jonap
https://spee.ch/jonap-part-2
https://spee.ch/the-great-savage

**Comment by MSFTserver** [comment]
ill see if its the spacing involved ima download your videos off lbry and re upload them to test,
i was also looking at the code it seem to use some sort of twitter player and i was reading there playing only supports up to a max size

**Comment by MSFTserver** [comment]
ok i just realized in my screenshot console is reporting the files are being interpreted as documents and trying to be served as mp3 so something went wrong

**Comment by billbitt** [comment]
Thanks for looking at this guys.  I will try to take a look today as well.  The twitter card should not be an issue, it's only used by twitter when the links are shared on twitter.  There may be size limits, but that won't affect or explain why they are not being played properly on spee.ch itself.

**Comment by MSFTserver** [comment]
ok so i can teh images to server corectly if i void out the /media and use the href link with .png at the end
would this be an option or is the /media needed for something?

**Comment by tzarebczan** [comment]
I also noticed this today with lbry://whatslbrybahasaindonesia1 - This one, in particular, may be a little different...the file starts to download on my end by never finishes, but normally these are still streamable (if encoded properly).  So if it's not encoded correctly, I think we need some type of overlay that says the file is still downloading/processing.  We also need a better way on the daemon side to restart downloads once they hang/fail, will research and open an issue.

**Comment by billbitt** [comment]
related to #213
