### ISSUE TITLE
Bug Report Form On Site

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/spee.ch#155]
i think it would be ideal for user who dont know how to use github if we had a webhook or api set up to send bug reports from a page already setup on the website with nice form feel for users and it will submit it as an issue on github

**Comment by tzarebczan** [comment]
There is already one under Help, report a bug.
It goes to our private slack and we investigate

**Comment by MSFTserver** [comment]
im more of talking about a page with form cause it just directs you to github to report the issue

**Comment by skhameneh** [comment]
We have social links to get in touch on the about page, but there is some friction associated with having to leave Spee.ch to file an issue.  This can be open to exploration, marking `icebox` since this is not a priority.
