### ISSUE TITLE
toggleSection function does not work in firefox 55.0.3

### ISSUE THREAD

**Issue by noliverio** [lbryio/spee.ch#159]
When interacting with an element that uses toggleSection in Firefox 55.0.3 no change to the page occurs and the following error appears in the debugger:
TypeError: event.srcElement is undefined

**Comment by noliverio** [comment]
I am proposing pull request #160 adding event.target to resolve this.

**Comment by filipnyquist** [comment]
Has been merged! @billbitt close

**Comment by billbitt** [comment]
oops, thanks @filipnyquist ;)
