### ISSUE TITLE
https://spee.ch/@grin should resolve to grin:1, not grin:2

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/spee.ch#163]
As grin, i'm confused about why my claims aren't showing up on spee.ch when they are showing up in `lbrynet-cli resolve @grin`

**Comment by billbitt** [comment]
Note for self: the `amount` and the `effectiveAmount` are incorrect in the spee.ch db.  Likely due to sync tool.

**Comment by skhameneh** [comment]
Fixed, resolves to active w/ supports
