### ISSUE TITLE
Filter out non supported file types from channels / speech in general?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#166]
I noticed that when it went to spee.ch/@jiggytom it had a txt file that I uploaded. I don't think we are supporting these types of documents on speech, so it may be a good idea to filter them out from channels and or spee.ch in general.  When you click on it, you get a hyperlink but can never download the txt file.

**Comment by MSFTserver** [comment]
alternatively if they are .txt documents... i noticed that the text document is still saved on the server if we change the <img> tag to <iframe> it will display that text file

**Comment by tzarebczan** [comment]
I just don't think we want speech to be used a a file sharing server.

**Comment by kauffj** [comment]
I have mixed feelings about this. I'm not necessarily opposed to spee.ch being used for PDFs or TXT assets. I'd lean towards saying if it's web viewable we ought to support it, though I also wouldn't prioritize this use case given limited capacity.

**Comment by MSFTserver** [comment]
if we were to use them we could have max .txt .pdf file size for now to help with space but i understand what you guys are saying, just some thoughts
