### ISSUE TITLE
markdown in github issue

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/spee.ch#172]
using the markdown in github works for loading the initial picture but when you click on it github throws an error wasn't sure if this could fixed on our end or an internal github issue

**Comment by MSFTserver** [comment]
![black-and-yellow](https://spee.ch/5af64e6041209483ea364f825e2f253e46341bf1/black-and-yellow.png)

**Comment by MSFTserver** [comment]
it might be looking for the meta data that we have issues with the fix might be in my other PR

**Comment by billbitt** [comment]
testing...

![test](https://spee.ch/2/githubdp.jpeg)

**Comment by billbitt** [comment]
![test2](https://spee.ch/2a6933d83f02ae15ed8020a2d51a2212a3292212/githubdp)

**Comment by billbitt** [comment]
seems like a github issue
