### ISSUE TITLE
Wrong filename when saving image

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/spee.ch#174]
![](https://i.imgur.com/sTa73Xe.png)

Look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by lyoshenka** [comment]
Or maybe its that the content-type of the whole page is html, not png?

**Comment by MSFTserver** [comment]
what browser i cant seem to reproduce this chrome gives the .png for both save image and save link as

**Comment by billbitt** [comment]
I am closing this because I cannot reproduce.  File names work fine for me; I believe this was a result of trying to save the whole page rather than the image.
