### ISSUE TITLE
Logging into a channel clears already filled fields

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#175]
I had filled out all fields before clicking "Login" on my channel. After clicking Login, all fields were cleared.

Additionally, I found it a bit confusing that I had to hit login in the first place. Could clicking Publish automatically login me in?

**Comment by billbitt** [comment]
I believe this issue is fixed, however we should discuss whether clicking Publish automatically logs you in / creates you channel.

**Comment by billbitt** [comment]
related to #231, regarding clicking Publish and automatically logging the user in / creating the user's chanenl

**Comment by billbitt** [comment]
will be fixed in #320
