### ISSUE TITLE
Publishing to a channel ought to give clearer feedback about channel-based URLs

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#176]
After publishing content to a channel, none of the URLs I am shown on the show page include my channel. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by mburstiner** [comment]
I've got someone taking a look at this this week!
