### ISSUE TITLE
Only use the canonical / permanent URL

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#184]
For SEO purposes, each discrete piece of content should only have a single canonical URL. Currently, in spee.ch, a piece of content can exist on up to 4 URLs:

- /file
- /claim/file
- /channel/file
- /channel:claim/file

All 4 of these pages should include a `<link rel="canonical">` tag to a single URL. That URL should be the one described by lbryio/lbry#958

More on these tags here: https://en.wikipedia.org/wiki/Canonical_link_element

Additionally, we ought to consider if an outright redirect (or JS based updating of the location bar) so that users are encouraged to use one URL over another. In particular, if content is published via a channel, we probably want to encourage users to use channel based URLs.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
The URLs described by lbryio/lbry#958 are the _only_ URLs that the app should directly send a user to and are the URLs that should be shown in all embed/share codes.

Additional URLs can resolve, but should include the canonical URL tag.

**Comment by daovist** [comment]
Most of this is done and live on spee.ch. Publishes are not yet using this feature. That will be part of the update-abandon PR upon which this ticket will be closed.
