### ISSUE TITLE
"No JSON object could be decoded" when retrieving claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#194]
Trying to get to https://spee.ch/@minutephysics:589276465a23c589801d874f484cc39f307d7ec7/bell-s-theorem-the-quantum-venn-diagram and you get a blank white page with "No JSON object could be decoded"

This content was originally attempted during spee.ch server issues on Thursday night

**Comment by billbitt** [comment]
from the logs: Request Error: /@minutephysics:589276465a23c589801d874f484cc39f307d7ec7/bell-s-theorem-the-quantum-venn-diagram No JSON object could be decoded

**Comment by billbitt** [comment]
@tzarebczan this error is coming from the daemon.  Should I file an issue?  From the lbrynet logs:

`2017-11-15 14:06:24,374 ERROR    lbrynet.daemon.Daemon:688: Failed to get bell-s-theorem-the-quantum-venn-diagram (No JSON object could be decoded)`

Also, I have not been able to reproduce on spee.ch.  Do you know of any other links that return this error?

**Comment by tzarebczan** [comment]
Let's take a look at this closer later today 

we should try running a file_list bell-s-theorem-the-quantum-venn-diagram to see if there was a previous failed download that could be causing this. Depending on what we find, an issue may be warranted on lbry

**Comment by tzarebczan** [comment]
@billbitt - can you check if this is still happening on the latest daemon and if so, please open an issue on lbry

**Comment by lyoshenka** [comment]
@billbitt can this be closed?

**Comment by billbitt** [comment]
closing.  Will open an issue on lbry if this persists
