### ISSUE TITLE
certain claim names shown as unavailable , others allowed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#197]
Not sure what the logic is which shows that a URL is already taken, but finding some discrepancies (see below). I think it checks taken names based on what's been uploaded through speech - don't think this is accurate right? Shouldn't we just allow uploads for any name since each claim will be unique and we aren't focusing on vanity claims?

Work:
jiggytom (I have a claim with this name)
profile (I have a claim with this name)
one -> ten (community claims which are taken)
itsadisaster (we have a front page item with this name)

Don't work:
lbry
lbry1
lbry2
bitcoin
test
a
d

**Comment by kauffj** [comment]
Due to the way `lbry` is currently implemented, spee.ch can only publish to a single name once. That is the current restriction, and it's entirely daemon side.

I thought this was open daemon side but couldn't find it, so I created https://github.com/lbryio/lbry/issues/953
