### ISSUE TITLE
speech resolving issues? Not showing winning channel claim

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#199]
I tried resolving https://spee.ch/@KazeEmanuar this morning and it leads to the old claim(6b5992e2cc667dddd3dfb7c6f8082f1fe33ef40f), it should be going to: https://spee.ch/@KazeEmanuar:8e098d2042ad9b9074f52cc06b89d6d4db5231dd

**Comment by MSFTserver** [comment]
same issue with current 404 page for lbry.io

**Comment by tzarebczan** [comment]
Per discussion with Bill, the effective amount was not updated properly, he's looking into it. Also, his current algorithm doesn't take into account the time delay for a takeover.

**Comment by tzarebczan** [comment]
This is also happening for spee.ch/nine - its resolving to 7289ed1bb8825471da886b40b59520fca19246bb but should be resolving to e5e538607b63b296ef7b11158349581b9e838c0c

Going back to the original claim in question, this is what Bill's output was showing:
6b5992e2cc667dddd3dfb7c6f8082f1fe33ef40f amount: 0.1 claimSequence: 1 effectiveAmount: 0.1
8e098d2042ad9b9074f52cc06b89d6d4db5231dd amount: 0.01 claimSequence: 2 effectiveAmount: 0

Effective amount of 0 is incorrect. When he ran a resolve, it showed the correct amount. Not sure if these are 2 separate issues, or all stem from the same root cause.

**Comment by MSFTserver** [comment]
might be useful informations but the 404 didnt break till i deleted the 404 claim all together then re uploaded a new one instead of just editing

**Comment by billbitt** [comment]
One problem was the datatype for `amount` and `effectiveAmount` was varChar not Double.  This has been fixed.
Another issue is that some claims are getting an effectiveAmount of 0 in the Claim or Certificate table.  I am not sure why yet, and this still needs to be fixed.  Likely an issue with the sync tool.

**Comment by tzarebczan** [comment]
Can you give me a list of which ones are coming up as 0. If they are takeovers, it may be related to this:https://github.com/lbryio/lbryum/issues/158
