### ISSUE TITLE
Drag-n-drop/ file chooser fails and doesn't show error

### ISSUE THREAD

**Issue by wilsonk** [lbryio/spee.ch#201]
The drag-n-drop functionality from the Thunar file manager to the web interface using Chrome (and Firefox) doesn't work. The dropped file just pops back over to the Thunar window. In the case of Firefox, there is simply no reaction at all to a dropped file.

**Comment by tzarebczan** [comment]
Do you have the same results on staging.spee.ch?

**Comment by wilsonk** [comment]
Haha, thanks for the suggestion on staging Tom...that revealed the problem! I had an apostrophe in the file name and that was messing things up. Staging showed an error message but spee.ch just failed silently.

Removed the apostrophe and thing worked fine.

**Comment by tzarebczan** [comment]
I noticed a similar issue with apostrophies and the lbry app, need to file it.

**Comment by billbitt** [comment]
note: spee.ch is still failing silently when an image with an apostrophe is dropped or selected, rather than showing the applicable error.

**Comment by billbitt** [comment]
closing as react refactor of publish tool renders this moot
