### ISSUE TITLE
Choose a file and publish doesn't work on Ubuntu clone

### ISSUE THREAD

**Issue by wilsonk** [lbryio/spee.ch#202]
Using the web interface for spee.ch on a Ubuntu clone (Linux Lite) allows me to choose a file by browsing to the file, but then I can't seem to publish to spee.ch. There is an error message in red letters inside the drag-n-drop window that says "Please select a file"...

I have tried to publish a photo anonymously and logged in and things fail both ways.

**Comment by wilsonk** [comment]
I just tried with the same file on Mac OS X and things worked fine. Just so you know :)

**Comment by wilsonk** [comment]
I would guess that this problem has to do with and apostrophe in the file name (the same as the #201).

**Comment by tzarebczan** [comment]
@wilsonk, closing this one right?
