### ISSUE TITLE
Social Media Sharing Links Not Working

### ISSUE THREAD

**Issue by Smurphonomics** [lbryio/spee.ch#204]
Many **social media** sites don't support sharing media files directly. Only the container page can be shared.

`
Share: twitter  facebook  tumblr  reddit
`

The current sharing code needs to be changed to omit the extensions, such as .**mp4**, .**jpg**, etc.

**Example:**

`
https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F8%2FMyVideo.mp4&amp;src=sdkpreparse`

**Needs to become:**

`https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F8%2FMyVideo&amp;src=sdkpreparse
`

Using a **RegEx** such as `(.+?)(\.[^.]*$|$)` should do the trick, but this is just a hack.

The correct solution is to make a pretty **permalink** for each file uploaded.

**Example:** www.spee.ch/ymok41cfpr

Or a user defined **permalink** with availability check:

**Example:** www.spee.ch/myvideo

**Comment by kauffj** [comment]
Thanks @Smurphonomics! I saw you are working on some LBRY related code as well. Are you in our chat?

**Comment by tzarebczan** [comment]
@kauffj he is FrontEnd on Slack.

**Comment by MSFTserver** [comment]
this more has to do with proper meta data for videos and sites i havent added yet was waiting for this redesign to go through to test out some new metadata https://github.com/lbryio/spee.ch/issues/178

**Comment by MSFTserver** [comment]
current meta-data:
```
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:site" content="@lbryio" />
	<meta property="og:title" content="spee.ch">
	<meta property="og:site_name" content="spee.ch">
	<meta property="og:type" content="website">
	<meta property="og:image" content="https://spee.ch/assets/img/content-freedom-64px.png">
	<meta property="og:url" content="http://spee.ch/">
	<meta property="og:description" content="Open-source, decentralized image and video hosting.">
```

im working on something like this:
```
	<meta property="og:title" content="spee.ch">
	<meta property="og:site_name" content="spee.ch">
	<meta property="og:type" content="website">
	<meta property="og:image" content="https://spee.ch/assets/img/content-freedom-64px.png">
	<meta property="og:url" content="http://spee.ch/">
	<meta property="og:description" content="Open-source, decentralized image and video hosting.">
	<!-- Twitter Card data -->
	<meta name="twitter:site" content="@LBRYio">
	<meta name="twitter:domain" content="spee.ch">
	<meta name="twitter:title" content="{{fileInfo.name}}">
	<meta name="twitter:description" content="Spee.ch - Decentralized Image Hosting using Lbry Protocol">
	<!-- Twitter Summary card images must be at least 120x120px -->
	{{#ifConditional fileInfo.fileType '===' 'video/mp4'}}
	<meta name="twitter:card" content="player">
	<meta name="twitter:player" content="https://spee.ch/{{fileInfo.name}}">
	<meta name="twitter:player:width" content="735">
  <meta name="twitter:player:height" content="449">
	<meta name="twitter:image" content="https://spee.ch/test.png">
	<meta name="twitter:image:width" content="735">
	<meta name="twitter:image:height" content="449">
	{{else}}
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:image" content="https://spee.ch/{{fileInfo.claimId}}/{{fileInfo.name}}.{{fileInfo.fileExt}}">
	<meta name="twitter:image:width" content="735">
	<meta name="twitter:image:height" content="449">
	{{/ifConditional}}
	<!-- google analytics -->
	{{ googleAnalytics }}
```

**Comment by MSFTserver** [comment]
no matter what link you put the meta data should be along these lines so twitter or facebook will pull that data to display whats at that link its also included on all the pages theres several ways to get to your picture to display it and something we need to work out i think

**Comment by MSFTserver** [comment]
i think theres like a total of 5 different links that can get to your image

**Comment by Smurphonomics** [comment]
Just to clarify, the bugs I am referring to are found on the social media HTML page links, as seen in the below image.

![image](https://user-images.githubusercontent.com/29914179/31701148-a1afa514-b411-11e7-81d3-0066c28eded1.png)

**Comment by Smurphonomics** [comment]
@kauffj The projects we are working on are pretty much the concept stage at the moment. The theme one is fairly straight forward. It will just inject custom pre-defined CSS.

The WordPress plugin idea is to pull in all videos from user defined channels, thus giving people the ability to host their own channels on their own websites, or show another users channel.

**Comment by MSFTserver** [comment]
i know what your refering to i tested and made those

**Comment by MSFTserver** [comment]
right now as i told billbit and posted in pr's i made, videos arnt ready till we work out the meta data for everything sorry if there was any confusion

**Comment by MSFTserver** [comment]
and the image your referring to is the thumbnail for the video not the actaul video so it should be an image file type heres the current code 
```
<a class="fb-share button" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F{{fileInfo.shortId}}%2F{{fileInfo.name}}.{{fileInfo.fileExt}}&amp;src=sdkpreparse">
```

**Comment by MSFTserver** [comment]
here my test from facebook for an image i tried video and im pretty sure that stems from meta data 
https://www.facebook.com/sawyer.lemmo.3/posts/775071969362720

**Comment by MSFTserver** [comment]
even using the shortened version its still meta data atm 
https://www.facebook.com/sawyer.lemmo.3/posts/779916832211567

**Comment by MSFTserver** [comment]
but if the shortened versions work after the meta data is fixed wouldnt mind trimming it down but just doing spee.ch/myvideo only returns the top claim for that url name no id would be necessary to get the correct claim

**Comment by Smurphonomics** [comment]
OK, new twist. Seems like the links do work, just as long as they **don't** have certain characters.

In my initial bug report on Slack, I presented the original url that **didn't** work.

`https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F8%2Fcvc-2.mp4&src=sdkpreparse`

I assumed it was the extension .mp4, that was creating the error.

I had changed the .mp4 to different extensions, such as .jpg. None of the links worked with any extension but it did work when I removed the extension. So I concluded that this was a social media restriction.

However; on further investigation, I've found that it was **not** the extension creating the issue after all, it was the `-2` part of the url when there is also a `.` after the `2` in the url.

Strange but true.

Anyway, the solution is simple. Just need to make sure `%2D` is used instead of `-`.

![image](https://user-images.githubusercontent.com/29914179/31719802-f31a0372-b457-11e7-86ba-c6c9c8db1a7a.png)

**Comment by Smurphonomics** [comment]
I tried sharing with this spee.ch link and it worked fine :)

https://spee.ch/a/Jason-Aldean-Tattoo-Matches-Illuminati-Card.mp4

Video was ripped from **YouTube** using:

`https://www.onlinevideoconverter.com`

A great way to preserve critical videos that usually get banned from YouTube.

A massive selling point for LBRY!

**Comment by MSFTserver** [comment]
ahhh ok so we need to encode/decode the uri, should be an easy fix

**Comment by MSFTserver** [comment]
ill change it to normal link then use `encodeURIComponent()` that should solve the issue

**Comment by Smurphonomics** [comment]
Ignore my "I tried sharing" post above. File name wasn't addressing the bug, but was an excuses to share some interesting Illuminati stuff, haha!

**Comment by MSFTserver** [comment]
@Smurphonomics also noticed in meta data there was `.` missing between filename and file extension last i checked @billbitt changed the syntax to not include the period in ext type and forgot to add it the meta data this may be another issue, also learned that facebook doesnt care about encoded `-` it will revert %2D back to `-` so that wasnt the issue either
#205 #206 #207 <- these may fix it(although probably should have made 1 pr out of it but if they ask ill do that)

**Comment by MSFTserver** [comment]
see where this gets us and proceed from there unless someone found the real root cause but i think its a multitude of things at the moment

**Comment by Smurphonomics** [comment]
Yeah. I didn't think it was a Facebook encoding issue after new discovery, rather an interference with their own markup or a security block to prevent SQL-Injections?

I didn't check to see if the link worked with `%2D`. You're right, it reverts back :(

`-2.` in that sequence was getting rejected, but worked fine in other sequences.

So I guess Facebook has a bug. Maybe the only other solution is to make sure URL's with this sequence `-2.`  are converted in to, lets say, `2.` ?

**Comment by MSFTserver** [comment]
upon testing it works for facebook without file extension, if i put a period after `cvc-2` it throws the 500 error not sure why the file extension on it would break it but its only for videos as this works either or 
`https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F8%2lbry-Background.jpeg&src=sdkpreparse`

`https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fspee.ch%2F8%2lbry-Background&src=sdkpreparse`

**Comment by billbitt** [comment]
The links are working for me now.  If this is still an issue lmk and we can reopen.
