### ISSUE TITLE
https://spee.ch/cop-chronicles - does not stream in Chrome Mobile

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#210]
The loading bar never finishes and it does not stream.

It works in the stock Samsung browser.

**Comment by billbitt** [comment]
is this on mobile, or desktop as well?

**Comment by tzarebczan** [comment]
Sorry, mobile.

**Comment by tzarebczan** [comment]
Turns out it was something to do with the encoding, not sure there's anything we want to do about it at this point.

**Comment by tzarebczan** [comment]
Closing this for now.
