### ISSUE TITLE
Speech should be able to re-download previously failed content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#213]
Take this claim for instance: https://spee.ch/@SandiaMesa:5dfb354a08cf4a589a366158af3aea445cdb6ce3/jonap - I was able to download locally recently. 

I think it was downloaded a while ago when spee.ch had issues and never completed properly. Spee.ch should recognize this scenario and re-download the content.  Right now it just looks broken. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by billbitt** [comment]
even after deleting (via the daemon, and record from spee.ch db) and downloading again, the link still does not work.

**Comment by billbitt** [comment]
related to #145

**Comment by skhameneh** [comment]
Needs further testing, relates to #209
