### ISSUE TITLE
`failed to download sd blob` displays an ugly error back to the user

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#225]
Problem: when a file request times out, it returns a text message to the user.

For example: https://spee.ch/chris45 returns `Failed to download sd blob 5c8dcdf4b311bb7c0bbbd58b0ad7d282edfb2aa4cfd9f35495ddd9bc5c4c53a942190965861a3be6d2127be707f761d0 within timeout`

As a user, If there is a problem accessing my content, I want to be told this in a clear way.  Ideally, I would like to be told immediately if the content is unavailable.

**Comment by tzarebczan** [comment]
related: https://github.com/lbryio/spee.ch/issues/185

**Comment by billbitt** [comment]
duplicate of #185
