### ISSUE TITLE
Improve UX around channel creation

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#231]
The UI between new and existing is generally very similar, and we should assume users will do one when they intend the other, regardless of any other changes.

There are several UI changes around channel creation to look at:

- It's not clear what the default between new and existing should be. It may be confusing to a new user that they have to use a select to get to the "New" form.
- If a user has entered a username and password for a non-existing channel, perhaps they should be offered to claim it?
- A user should not be forced to click create channel when on New. If I enter a channel and a password and then click submit with everything else valid, just submit both for me.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
Added third item.

(Does GitHub give any notification for substantial edits?)

**Comment by billbitt** [comment]
related to #175
