### ISSUE TITLE
Channel not found on spee.ch (DoorMonster, possibly others?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#244]
Story: As a user, I want to view my lbry channel on spee.ch, so that I can see and share my free content.

Problem: some channels (see below) are not being resolved on spee.ch. User gets the 'no channel' page or an error page.  In the latter case, the error seems to be related to looking up short ID for channel that it cannot find.

**Comment by billbitt** [comment]
When we featured the DoorMonster content last week, I noticed that https://spee.ch/@DoorMonster was not coming up. Bill looked into it:

```
so I checked the db and didn't see a claim record for it and thus assumed it didn't get synced.  I set the sync tool back a bunch of blocks thinking it would catch it, but I guess it never did.  I'll have to take another look

answer is yes, it could be happening to others, although I haven't heard anyone coming across it
```

**Comment by billbitt** [comment]
The issue appears to be related to the channel not having a record in Certificate table. I.e. not being upserted by the sync tool.

https://spee.ch/@DoorMonster
https://spee.ch/@Zeb
https://spee.ch/@DerickWattsAndTheSundayBlues

**Comment by billbitt** [comment]
I updated the sync tool to use sequelize and cleaned up the database updates.  This seems to have fixed the problem.  The tool is re-syncing to get missed claims now.
