### ISSUE TITLE
Redirect all urls through https://spee.ch

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#258]
issue raised by @Smurphonomics 

The URL still needs to be canonicalized/redirected though. Search engines will class http://, https://, http://www/. and https://www/ all as seperate sites. It will also interfer with Google Analtics data.

The site should be resolve to one prefered url server side.  Example https://spee.ch/(edited)

@lyoshenka, it looks to me like http:// does already redirect to https://, can you have www.spee.ch redirect to spee.ch ?

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment]
That's something you have to do in the app. i bet there's middleware for
this.

**Comment by kauffj** [comment]
@lyoshenka if the redirects are 301s, it's probably better to have the web-server handle this.

@billbitt for non-redirects, @Smurphonomics is right on, and you should add `rel=canonical` tags (see https://en.wikipedia.org/wiki/Canonical_link_element).

**Comment by Smurphonomics** [comment]
Yoast is always good with these things. Here's his run down.

https://yoast.com/rel-canonical/

**Comment by Smurphonomics** [comment]
As for redirects, I usually put a regEx in the .htacess file, but it's better being done via the server.

https://httpd.apache.org/docs/2.4/rewrite/remapping.html.

You have to have a giggle at the note Apache put at the top of that page. :p

**Comment by lyoshenka** [comment]
Still think this is easiest to do in the app. @billbitt lemme know if you want me to help with this

**Comment by kauffj** [comment]
Not very useful without https://github.com/lbryio/lbry/issues/958

Or at least, only fixing about 1/3 of the problem without above

**Comment by daovist** [comment]
@nikooo777 did this with caddy on spee.ch: http://www.spee.ch/about

@jessopb is working on refining the installation process which will include the same setup. I'm leaving the issue open until this is tested on new instances.
