### ISSUE TITLE
Set up virtual instance of Spee.ch

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#264]
Story: As a front end developer, I want to be able to run spee.ch locally so that I can work on the design, but I don't want to have to worry about setting up the back end and getting it running.

Solution: @Smurphonomics suggested deploying a virtual machine image so people can download and run for debugging with no issues on any device.  He suggested Virtual Box and Vagrant.  I spoke with @wilsonk and he suggested we set up a docker container.  @kauffj @lyoshenka any suggestions or input?

**Comment by lyoshenka** [comment]
​I'd lean towards docker. It's easier to maintain than a VM, esp when
things change. Let me know if you want help with this, or if you want to
figure it out. I'm not a docker expert but I've used it some.

**Comment by Smurphonomics** [comment]
> Containers provide OS-level process isolation whereas virtual machines offer isolation at the hardware abstraction layer (i.e., hardware virtualization).  So in IaaS use cases machine virtualization is an ideal fit, while containers are best suited for packaging/shipping portable and modular software. Again, the two technologies can be used in conjunction with each other for added benefits—for example, Docker containers can be created inside VMs to make a solution ultra-portable.

https://www.upguard.com/articles/docker-vs.-vmware-how-do-they-stack-up

**Comment by skhameneh** [comment]
@Leopere, you might want to sync up with @jessopb 😃
