### ISSUE TITLE
claim ids or other long words do not break to next line on error display

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#265]
Claim ids, or other long words, do not break to next line on error display.  See below:

![screenshot 2017-11-14 17 34 23](https://user-images.githubusercontent.com/19243959/32808828-686774ec-c962-11e7-85ae-ab41c1be8793.png)

**Comment by Smurphonomics** [comment]
Not managed to get the app working locally yet, so can't test this one, but try giving the container div/span class a display value of block.

Example:

.error {display:block;}

**Comment by Smurphonomics** [comment]
https://github.com/lbryio/spee.ch/pull/267
