### ISSUE TITLE
update /popular page to use an optimized asset-preview component for each asset

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#270]
Story: As a user, I want the popular page to load quickly so I can view the popular content quickly and without confusion.

Problem: the page loads pretty quickly, but the content takes a while to load, and the content shifts around as it loads due to masonry.js figuring out the best way to lay it out.  

One aspect of the solution is probably to load a thumbnail for big gifs rather than the full gif itsself.  related: https://github.com/lbryio/spee.ch/issues/152

Another related but different issue with the popular page is the thumbnail for the videos not being the actual thumbnail: https://github.com/lbryio/spee.ch/issues/220

**Comment by billbitt** [comment]
I think I️t would be best to create a card-type component with fixed proportions so that masonry can be removed and the display can count on being able to tile them at fixed proportions.

**Comment by billbitt** [comment]
Perhaps only load 10 at a time, but implement infitine scrolling so it keeps requesting the next 10 automatically

**Comment by kauffj** [comment]
@billbitt if you store the image/thumbnail width and height in the database so that they are available at render time, I bet you can get masonry to render a lot faster.

AFAIK there is no way to get a truly masonry-like layout without javascript.

**Comment by billbitt** [comment]
replaced by #336
