### ISSUE TITLE
Investigate best way to add Sass to the project and/or reorganize CSS

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#272]
add Sass to manage css 
http://sass-lang.com/

**Comment by lyoshenka** [comment]
@billbitt if you're gonna tag this "good first issue", you should write it up some more. where do the sass files go, and where does the built css go? how does this fit into building the site (or is all sass compiled on the fly)? etc

**Comment by billbitt** [comment]
Got it.  I'm moving this back to 'on deck' so it can be groomed and removing `good first issue` until it is groomed.
