### ISSUE TITLE
Add Instagram to the 'share' list

### ISSUE THREAD

**Issue by wilsonk** [lbryio/spee.ch#274]
My daughter asked if she could share a post from spee.ch on Instagram. I noticed it wasn't on the list of places to share a post, so I thought I would past here to ask for this feature addition :)

**Comment by MSFTserver** [comment]
@wilsonk i looked into it i didnt add it since instagrams one job was to include an api to publish but they dont so this is not possible at the time

**Comment by MSFTserver** [comment]
theres is currently one way but that include a MITM attack wich i wont include

**Comment by MSFTserver** [comment]
if there was a separate app for mobile apart from the main speech site we could include both ios and android webhooks but on PC it inst possible yet without a MITM attack and reverse engineering of the api which break TOS

**Comment by wilsonk** [comment]
Ok, great @MSFTserver, thanks for that information. I will let Bill close this, if he feels it is necessary, or we can leave it open and look into it in the future again.
