### ISSUE TITLE
Show URLs are no longer serving assets when embedded in <img> tags

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#275]
`lbry://zackmath#8` has a metadata thumbnail value of `https://spee.ch/zackmath`.

This used to display `https://spee.ch/zackmath.png` in the App, but no longer does.

**Comment by billbitt** [comment]
I don't think this is an issue of serving the direct asset; it appears to be a problem of spee.ch not having a record for `zachmath` in it's Claim table.  I am going to change the issue name accordingly.

**Comment by billbitt** [comment]
I wonder, was this specific claim properly served by spee.ch at one time and is now broken, or was it never served properly?  
Could be related to the issues with the sync tool not getting all claims into the relational blockchain db.

**Comment by kauffj** [comment]
I typed the name wrong in one place. It's there. See https://spee.ch/zackmath
