### ISSUE TITLE
show links are not unfurling on social media

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#281]
https://spee.ch/1/Lbryshirtlunch - picture
https://spee.ch/letitsnow - vid w/ thumbnail
https://spee.ch/lbrydevelopment - vid w/o thumbnail

both of these should unfurl to show something when shared in slack, facebook, twitter, etc.

**Comment by kauffj** [comment]
Possibly changed by https://github.com/lbryio/spee.ch/pull/276 ?

Both pages contain `og:image`, no reason I can think one should work but not the other.
