### ISSUE TITLE
add thumbnail selection tool to publishing process

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#282]
As a user, when I select a video for publish, I want to be able to select a frame from that video to be the thumbnail so that I can set the thumbnail easily during the publish process.

**Comment by billbitt** [comment]
@kauffj, assuming a thumbnail is chosen (ideally via a slider), once it is chosen should spee.ch publish that frame to spee.ch before setting it as the thumbnail?

**Comment by kauffj** [comment]
@billbitt yes
