### ISSUE TITLE
Spee.ch stuck on loading file, it's published but blank

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#284]
When uploading a claim to a channel, upload gets stuck on the last screen before showing the resulting claim. When you go to the claim manually, it has metadata but the file is blank.

I usually upload in a background tab - not sure if that has anything to do with it. 

Here is one example: https://spee.ch/not-selling

@billbitt would go in and have to delete the file, and have it be re-created from the blobs.

**Comment by billbitt** [comment]
https://spee.ch/lbrysubscriptions

**Comment by billbitt** [comment]
I'm having trouble recreating the issue, but I think I can figure it out by looking at these links that are broken.

**Comment by billbitt** [comment]
I just got it to happen in my browser so confirmed it is not something unique to your setup @tzarebczan

**Comment by billbitt** [comment]
the hanging issue is related to daemon not responding in time.  fixes besides speeding up daemon: (1) if response times out, update the display (2) stop temporary file from being deleted so that on refresh the content is available
