### ISSUE TITLE
Add open.lbry.io link to in-app content on all spee.ch pages

### ISSUE THREAD

**Issue by Feanor78** [lbryio/spee.ch#286]
It would be great if we could add a link that opens both channels and videos in-app (and notation that makes it clear that that's where the link points) for videos on spee.ch, that would be awesome and very useful for driving people to the app via social.

**Comment by jsigwart** [comment]
I think we should add text to every speech page (including the published file pages) that says something like "powered by LBRY" with a link to the app download or at least the main page.

**Comment by tzarebczan** [comment]
@jsigwart your suggestion is a separate issue, which was filed here and then closed: https://github.com/lbryio/spee.ch/issues/377

**Comment by tzarebczan** [comment]
We'd probably want a link to the LBRY app in this case, so need to reconsider: https://github.com/lbryio/spee.ch/issues/377

**Comment by kauffj** [comment]
@robvsmith can you supply copy for this? What do you think of something a little more sales-y, like
"Watch on LBRY and earn xxx" ?
