### ISSUE TITLE
'Cannot read property \'startsWith\' of null'

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#288]
new error popped up: `message: 'Cannot read property \'startsWith\' of null'`
has to do with claim url parsing

**Comment by billbitt** [comment]
looks like this is happening when a client tries to access `https://spee.ch/:` in the browser.  I am going to patch the route so it does not error, but the real issue is why that link is being visited.  it is likely a user trying to visit their channel page, but the url is not being generated correctly by the template engine.  I.e. it means to create a link to `spee.ch/@example:exampleId` but ends up with `spee.ch/:' because the channel name and channel id are empty.

**Comment by lyoshenka** [comment]
closed by lbryio/spee.ch#310
