### ISSUE TITLE
google analytics should track direct request that do not get logged via client-side script

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#295]
Story: As a developer, I want to see direct requests for access logged in google analytics so that I can understand how much the site is used outside of typical in-browser visits.

Issue: at the moment, the google analytics script is being inserted into handlebars templates by the server, so google analytics are not being logged by requests for assets that are handled by the server without sending back an html page.  

Solution: This issue is solved for publish requests by using the `universal-analytics` npm package to send info directly to google via the server.  This can be added to the `serve` route as well.

**Comment by Smurphonomics** [comment]
Can you give more details as to why you think some visits aren't being tracked?

**Common reasons are:**

1) GA code doesn't load in quick enough before the visitor bounces.

2) Visitor (which includes me) has a Google opt out browser plugin.

[GA Opt-Out](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en-GB)

3) Visitor has other tracking prevention plugins.

4) Code error.

5) A visitor who is logged in to a Google account automatically has their details hidden - Strange but true.

Quote: "The keyword (not provided) describes organic searches that are being hidden from your view, to provide a measure of privacy for users. In 2011, Google began encrypting results from SSL searches (secure searches from users who are logged in to their Google Accounts or using the Firefox search bar)."

**Comment by kauffj** [comment]
@Smurphonomics I suspect this may be as simple as the code not being included in some views.

@billbitt did you look into this? I still see a change in numbers starting on 12/14 or 12/15 that makes me think something is wrong here.
