### ISSUE TITLE
Show What Media Type

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/spee.ch#316]
When someone visits a channel, they can't see what type of content is being shown, such as MP4, JPG, GIF, etc. An icon placed on top of the thumbnail depicting what media type it is would solve this.

Alternatively, items could be grouped by media type.

**Comment by billbitt** [comment]
I like the idea of an icon.  Perhaps also when the user mouses over it could show some information like title and media type.

**Comment by Invariant-Change** [comment]
Should be pretty easy to do. I'll look into it.

**Comment by tzarebczan** [comment]
closing in favor of #926 - we have basic media type icons now.
