### ISSUE TITLE
Hardcoded LBRY API JSON address

### ISSUE THREAD

**Issue by maximest-pierre** [lbryio/spee.ch#324]
Inside helpers/lbryApi.js the API location is always Hardcoded. This means that the LBRY daemon must always be ```localhost:5279/lbryapi```. if we set it with a config file, we can split the dependency to multiple machines for deployment. This would also help to make a replicable dev environment with docker.

**Comment by kauffj** [comment]
Good call @maximest-pierre! This should probably be in the `lbrySettings` part of `package.json`.

**Comment by maximest-pierre** [comment]
I am probably going to fix this today. When I get a chance.

**Comment by kauffj** [comment]
Oops, this isn't `lbry-app`. I suppose it would go in speechConfig.js? @billbitt should affirm this.

**Comment by maximest-pierre** [comment]
I think this will go here ```spee.ch/config/speechConfig.js.example```
