### ISSUE TITLE
update /popular page to render faster, without broken links

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#338]

**Comment by Smurphonomics** [comment]
Something like this would help.

A lightweight but powerful delayed content, image and background lazy-loading plugin for jQuery & Zepto

http://jquery.eisbehr.de/lazy/

As for broken media, might be better to run a script to fix or remove them, rather than filtering them?

**Comment by kauffj** [comment]
@billbitt I suspect storing image width and height in the spee.ch db would be a good idea.

**Comment by Smurphonomics** [comment]
I'm trying this out - Might be a good concept for Speech?

https://cloudinary.com
