### ISSUE TITLE
'in a channel' should be selected by default for publishing if a channel is logged in

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#344]
Story: As a user, If I am logged in to a channel and I select a piece of content to publish, 'in a channel' should be selected as the default option.

**Comment by billbitt** [comment]
I updated this to 5 points because I started working on this last sprint and it will require some non-trivial changes to the the way state is handled for the component

**Comment by kauffj** [comment]
@billbitt I made a note to discuss this on our next meeting, I have some thoughts on design here I'm too lazy to write out atm.

**Comment by Smurphonomics** [comment]
I was just about to file this issue.

So many times I upload and forget to select channel after logging in. I then have to re-upload within the channel when I realise.

**Comment by billbitt** [comment]
thanks @Smurphonomics.  I moved this to the top of the queue

**Comment by billbitt** [comment]
suggestions from standup: this widget should remove the radio and jsut have anonymous as a selection option.

**Comment by alyssaoc** [comment]
related to #231
