### ISSUE TITLE
Using spee.ch from a web app

### ISSUE THREAD

**Issue by esteem8** [lbryio/spee.ch#354]
Hello,

I know that it is possible to embed files in general into any  web application by simply using the file url but I wonder if it also is possible to directly use spee.ch to publish content instead of using the official JS API.

Thanks in advance.

**Comment by tzarebczan** [comment]
Are you looking to upload content to speech via an api? This possibly? https://github.com/lbryio/spee.ch/blob/master/README.md#api

**Comment by esteem8** [comment]
Holy grail found!
Thanks, was just blind^^
