### ISSUE TITLE
Does anyone have an example for using the API in JS?

### ISSUE THREAD

**Issue by esteem8** [lbryio/spee.ch#355]
Hello,

I've tryed to publish content using XMLHttpRequest in JS.
I come to have a file object which is uploaded:

I don't know how to make it work, I've tried with the file source in `base64` and with the whole object using
```
let form_data = new FormData();
form_data.append("file", file);
// Some stuff
xhr.send(form_data);
```

but it doesn't seem to work :/

Thanks

**Comment by kauffj** [comment]
@esteem8 please share your full code so @billbitt can understand why it's not working.

**Comment by esteem8** [comment]
Maybe it would be easier if someone could give a working example of using the POST API in JS using the common XMLHttpRequest method.

**Comment by nikooo777** [comment]
here is a working example. the API described in the README is actually not up to date (thanks @tzarebczan )

```
let data = new FormData();
data.append("name", "apitest");
data.append("file", "C:\\Users\\Niko\\Downloads\\litsmokeoverlugano.jpg");
data.append("nsfw", "false");
data.append("title", "this is an api test");
data.append("description", "This API is cool and so is my pic");
data.append("thumbnail", "https://scrn.storni.info/ApplicationFrameHost_2018-02-20_01-02-13.jpg");

let xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://spee.ch/api/claim-publish");

xhr.send(data);
```

or using jQuery:

```
let form = new FormData();
form.append("name", "apitest");
form.append("file", "C:\\Users\\Niko\\Downloads\\litsmokeoverlugano.jpg");
form.append("nsfw", "false");
form.append("title", "this is an api test");
form.append("description", "This API is cool and so is my pic");
form.append("thumbnail", "https://scrn.storni.info/ApplicationFrameHost_2018-02-20_01-02-13.jpg");

let settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://spee.ch/api/claim-publish",
  "method": "POST",
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```


suggestion: you can try the API using Postman: https://www.getpostman.com/
it lets you generate the code for your app as well: https://scrn.storni.info/Postman_2018-02-20_02-01-50.png

**Comment by nikooo777** [comment]
yesh, if you're specifically looking for a status 200 then yes

**Comment by Smurphonomics** [comment]
Might be better for future debugging to have that extra layer in?

**Comment by kauffj** [comment]
@nikooo777 this is great, can you add this to the `README`?

**Comment by nikooo777** [comment]
i'd like to first discuss another option with @billbitt as i think there is a better solution

**Comment by esteem8** [comment]
Does it work with addresses such as "blob:http://localhost:8080/362b4952-904d-49fa-9d0b-90041836fce8"?

**Comment by nikooo777** [comment]
i'm sorry, what do you mean?
What are you trying to achieve and what isn't working?

**Comment by esteem8** [comment]
Well, cant get the full pathname when uploading a file, is there an other solution instead of specifying a full absolute path such as `form.append("file", "C:\\Users\\Niko\\Downloads\\litsmokeoverlugano.jpg");` ?
Something like `"blob:http://localhost:8080/362b4952-904d-49fa-9d0b-90041836fce8"` or even the blob?

**Comment by nikooo777** [comment]
this is not possible as far as I am aware, the file must come from your computer and it must be a file that the final user will be able to stream or otherwise open. A blob would result in a useless file that can't be opened.

You must have access to the file itself otherwise how can you publish it?
If you're writing an HTML+JS page you'd want a File input to let the user select the file, and from there you should have your path to the file or something similar (the file itself perhaps)

**Comment by esteem8** [comment]
In JS you might use node.js.

**Comment by nikooo777** [comment]
if you use Node.js then i'd suggest also making use of request

```
const fs = require("fs");
const request = require("request");

let options = {
	method: 'POST',
	url: 'https://spee.ch/api/claim-publish',
	headers:{
		'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
	},
	formData:{
		name: 'apitest',
		file:{
			value: 'fs.createReadStream("C:\\Users\\Niko\\Downloads\\IMG_20170225_151638.jpg")',
			options:{
				filename: 'C:\\Users\\Niko\\Downloads\\IMG_20170225_151638.jpg',
				contentType: null
			}
		},
		nsfw: 'false',
		title: 'this is an api test',
		description: 'This API is cool and so is my pic',
		thumbnail: 'https://scrn.storni.info/ApplicationFrameHost_2018-02-20_01-02-13.jpg'
	}
};

request(options, function (error, response, body) {
  if (error) throw new Error(error);
  console.log(body);
});
```

**Comment by billbitt** [comment]
@esteem8 were you able to get this working properly?

**Comment by esteem8** [comment]
No only from Node.js.
I need to set up a proxy... +1

**Comment by esteem8** [comment]
@billbitt No only from Node.js
I need to set up a proxy for using it in a browser...

A way to fork speech in order to use LBRY as an image hoster for a client web application or a markdown file to present how to do it simply is tremendously appreciated^^
