### ISSUE TITLE
The API should be specified in swagger

### ISSUE THREAD

**Issue by nikooo777** [lbryio/spee.ch#357]
Currently the API is briefly described in the README however as a potential API user I'd like to have it described in Swagger so to be able to quickly generate an SDK or even better contribute in its implementation.

What is swagger? https://swagger.io/docs/specification/about/

how does it look like? 
I implemented it for spee.ch so that you could take a look at it and decide whether it's worth it or not. here it is:
https://app.swaggerhub.com/apis/nikooo777/spee.ch/1.0.0

The swagger specification is a simple YAML file so that can be uploaded to the root of the project or wherever it makes sense to keep it.

A swagger document can also be imported in AWS to generate an API on the fly.

If you like this idea I'll make a PR to include it in the project.

**Comment by alyssaoc** [comment]
@nikooo777 please reach to spee.ch team for discussion

**Comment by alyssaoc** [comment]
Did you want to pick this back up?

**Comment by kauffj** [comment]
I think this is fairly low priority. We don't really want 3rd-parties using the spee.ch API; it's better they use LBRY directly. This API is/would be useful if/when we have more active 3rd-party usage of spee.ch and such parties want to use it.
