### ISSUE TITLE
Add support for the oEmbed standard to enable automatic embedding

### ISSUE THREAD

**Issue by seigler** [lbryio/spee.ch#358]
oEmbed is a standard used to turn a content URL into a JSON or XML data block with details on embedding the content in an arbitrary webpage, including HTML markup.

The standard at https://oembed.com/ is clearly written and the requirements are pretty mild.

**Comment by seigler** [comment]
This article from Y Combinator lists all the hoops (including oEmbed) you have to jump through to get embedding on various popular websites, including Slack, Reddit, Medium, and the many many sites using Embed.ly.

https://blog.ycombinator.com/how-to-build-an-oembed-integration-for-your-startup-and-why-its-necessary/

**Comment by billbitt** [comment]
@skhameneh fyi ;)

**Comment by billbitt** [comment]
to dos:
- [ ] add height and width for media to DB ()
- [ ] add oEmbed tags to header (https://oembed.com/#section4)
- [ ] add api route for oEmbed consumer requests (https://oembed.com/#section2)
- [ ] test
- [ ] get whitelisted by embed.ly
- [ ] test on reddit, mastadon, etc.
- [ ] get whitelisted by any other sites that require whitelisting (e.g. medium)

**Comment by billbitt** [comment]
creating a separate ticket for becoming an embed.ly provider:  https://github.com/lbryio/spee.ch/issues/544
