### ISSUE TITLE
Enable client side API usage

### ISSUE THREAD

**Issue by esteem8** [lbryio/spee.ch#365]
The API can be used for free with any server using any programming language.

But when using the API from a client JS application running in a browser the query is not working:

`Failed to load https://spee.ch/api/claim-publish: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://viper-network.github.io' is therefore not allowed access.`

The problem seem to be the .htaccess file or it can result of a misleading usage of AJAX.

I think that it would be very great for many application and the LBRY client could be tested in demo using a simple web browser.

**Comment by billbitt** [comment]
@esteem8 can you provide some steps on how to reproduce this issue?  For example, the code in your client JS application that is making the call?

**Comment by billbitt** [comment]
note the discussion in https://github.com/lbryio/spee.ch/issues/368 regarding how to use `xhr` from the browser client-side and `request` in node

**Comment by esteem8** [comment]
It don't work from a browser but do work using node.js.
Therefore a proxy must be provided or the spee.ch .htaccess file must be updated.

Thanks for providing us a response in regards of the taken decision.

**Comment by esteem8** [comment]
I really wonder about api-forms, client side usage, pricing issues and payment systems, along with .htacess opening on speech regarding browser usage.

I know the importance of this issue, thanks for the consideration.

**Comment by alyssaoc** [comment]
possibly considering this in the future, closing for now
