### ISSUE TITLE
Create FAQ for spee.ch

### ISSUE THREAD

**Issue by jsigwart** [lbryio/spee.ch#369]
Answer common questions like what video formats are supported, channel basics, etc.

**Comment by LavRadis** [comment]
I'm interested in contributing :-) Who is the person too coordinate this with?

**Comment by billbitt** [comment]
@LavRadis lmk if you want to work on this.  @tzarebczan and I can answer any questions you have via discord or we could set up a google hangouts

**Comment by LavRadis** [comment]
@billbitt yes, I'll work on that :-) I'm open to any suggestions from your side!

**Comment by heymattsokol** [comment]
Is this issue still open? I could take over. @LavRadis lemme know

**Comment by LavRadis** [comment]
@heymattsokol It was a long time in the planning but somehow it got forgotten due to some other project activities :-) We can re-start it and coordinate with @billbitt

**Comment by jsigwart** [comment]
@LavRadis @heymattsokol this issue is still open. Either of you guys want to take a stab at it?

**Comment by heymattsokol** [comment]
Aye, the FAQ @tzarebczan linked is the one that I wrote 13 days ago. It is merged into the @LavRadis branch as a readme. 

I'll submit a new merge request to Lav where the text actually shows up on the site's About page, and then he can merge it / PR it to the main branch.

**Comment by tzarebczan** [comment]
@heymattsokol / @LavRadis can we revisit this again?

**Comment by heymattsokol** [comment]
I have no idea what we are waiting for. @LavRadis can you please explain where we are at?

**Comment by LavRadis** [comment]
sorry, I just got stuck on this one :-) (and had a short vacation)

**Comment by heymattsokol** [comment]
Cool -- Do you want to push the merge request? Or if there's any error in the code I submitted (Entirely possible), I'm happy to redo.

Basically - Lav, here is my question: What is the next action step?

**Comment by heymattsokol** [comment]
We got it worked out! I believe that Lav is pushing the final FAQ (text only) to the main branch now.

**Comment by tzarebczan** [comment]
This is now live: https://spee.ch/faq
