### ISSUE TITLE
Add LBRY app download link to spee.ch content pages

### ISSUE THREAD

**Issue by finer9** [lbryio/spee.ch#377]
near where it says 'hosted by spee.ch'

**Comment by billbitt** [comment]
I'm actually not a huge fan of putting this on the asset pages, because I think it is good to keep a separation between spee.ch - and any other lbry implementations - and the app.  I think having a link to download on the `spee.ch/about` page is sufficient.  lmk if you disagree @finer9.

**Comment by jsigwart** [comment]
I disagree - right now spee.ch is an excellent functional demo of a LBRY implementation. There is no confusion between spee.ch branding and LBRY - they are very distinct. Not promoting the LBRY technology on every image page is a missed opportunity.

**Comment by billbitt** [comment]
ok, I'm convinced @jsigwart ;)
