### ISSUE TITLE
White lines on top and bottom in full screen mode 

### ISSUE THREAD

**Issue by LavRadis** [lbryio/spee.ch#389]
While watching https://spee.ch/e/heli.mp4 I've noticed a white line on the top and bottom of the screen. Tom sees only one on top, Chris sees both. I'm using Chrome on Win 10. 
![untitled](https://user-images.githubusercontent.com/10566738/37309929-bab46538-2642-11e8-9de5-33bf01811449.jpg)

**Comment by billbitt** [comment]
I've also noticed that on videos with these proportions, the 'hosted via spee.ch' link gets covered by the video

**Comment by billbitt** [comment]
@LavRadis the white line issue you are describing is when the video is full-screened, correct?

**Comment by LavRadis** [comment]
@billbitt  yes.

**Comment by billbitt** [comment]
@LavRadis oops, I'm an idiot, you said 'full screen' in the title of the issue

**Comment by Smurphonomics** [comment]
Fixed here: #414
