### ISSUE TITLE
decide on a pattern for user configuration of the spee.ch package

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#392]
We need a pattern for how we will design the spee.ch package to accept user configurations.  Will this be done with config files, dynamic loading of custom components, a cms editor, or something else?

**Comment by esteem8** [comment]
I would need to fork it in order to make file upload feasible from client side JavaScript,
 * Clarifying hosting price would be very appreciated
 * Clarifying configuration and cross-domain too

Feel free, I would need it

**Comment by billbitt** [comment]
After discussion with team we decided to pursue a pattern where custom components will be passed to the build via a config variable.  This pattern worked for server side rendering, but does not work for the client bundle.
