### ISSUE TITLE
File saved as HTML when clicking Download button

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#408]
When clicking the download button here: https://spee.ch/332fb1627fc3b982cc991da0ada2c09688be8a0c/A-Work-of-Art - the file attempts to be saved as HTML. Seems to happen on gifs and mp4s as well.

**Comment by lyoshenka** [comment]
![](https://i.imgur.com/gYoSX6y.png)

My guess is that its related to setting the Content-Disposition header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
