### ISSUE TITLE
Support claim updates which include content updates

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#418]
Logging as a result of https://github.com/lbryio/www.spee.ch/issues/6#issuecomment-382715220. This will require chainquery.

https://spee.ch/droid1 - I uploaded a different image but spee.ch still serving the original.

**Comment by jessopb** [comment]
Currently, in getClaimIdAndServeAsset, we do this to find the file to serve:
```
.then(() => {
      return db.File.findOne({
        where: {
          claimId,
          name: claimName,
        },
      });
    })
    .then(fileRecord => {
      if (!fileRecord) {
        throw NO_FILE;
      }
      serveFile(fileRecord.dataValues, res);
    })
```
To do this well, we need to call lbrynet get to verify we have the latest claim (or any at all), display progress bar and messaging for the server getting the file, route the file through any necessary processing (based on querystring i.e. height=x), then serve the file.

This seems like it's already done once and needs a DRY analysis.

**Comment by jessopb** [comment]
lbrynet get / file_list returns filename, and provides the necessary information to see how much of the file has been downloaded, and reports when status is completed.
