### ISSUE TITLE
Sorting content on channels should match LBRY app (newest first)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#421]
Breaking this issue out from the comment here for visibility: https://github.com/lbryio/spee.ch/issues/359#issuecomment-372535758. Currently speech sorts content on channels by oldest first. I've seen times where the newest updates appear first for a short period of time, not sure when/why that happens. 

See https://spee.ch/@TheRubinReport / [lbry://@TheRubinReport](https://open.lbry.io/@TheRubinReport)

**Comment by billbitt** [comment]
reopened, because this is merged into master but not live on spee.ch production yet.  will close when live.
