### ISSUE TITLE
content is found, but the asset is broken on page (404 not found from server)

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#426]
e.g. https://spee.ch/36fa3eac6ffd0d6550baeaabb8b267d80e445352/cookies
- [ ] figure out what is causing the error
- [ ] ensure these errors are being logged (to slack, etc.)

**Comment by jessopb** [comment]
For the first part, the file is in the local speech db, and the code picks the newer record between local db and chainquery to call file load on.  The file referenced in the db, /home/lbry/Uploads/HhJ_HmFuqaXJuUOzTx3BBPp4.jpg doesn't exist. Deleting the file should solve this particular problem. Going forward, The code picking the newer db record should keep a fallback in case the file could not be loaded locally. We also want to run a comparrison between Uploads and Downlodas dir and localdb to find any further discrepencies.
Logging to be explored.

**Comment by jessopb** [comment]
The same lbrynet get call that gets the file information for file extension also rebuilds any missing files, or reports that it already exists. Lex says lbrynet get is highly optimized and that calling it on every request shouldn't be a problem.
