### ISSUE TITLE
Auto Login seems buggy and does not occasionally 

### ISSUE THREAD

**Issue by ceoger** [lbryio/spee.ch#440]
I have my spee.ch login credentials saved in my browser, when i opened and it was automatically filled but i was unable to log in, i have include a screenshot of the message i am getting, seems there are other issues as well...
![spee](https://user-images.githubusercontent.com/38915222/39770831-b43461f8-52df-11e8-9c26-4686b62839c6.JPG)
![sp1](https://user-images.githubusercontent.com/38915222/39770832-b488b686-52df-11e8-9255-50f31fe3d9cb.JPG)
![sp2](https://user-images.githubusercontent.com/38915222/39770834-b661dc3a-52df-11e8-8c7e-cdc683ad833d.JPG)

**Comment by tzarebczan** [comment]
@ceoger are you sure this channel was created on the main spee.ch site, and not the staging.spee.ch one? That's one possibility. Were you able to login previously? Maybe the password was updated incorrectly somewhere? 

If none of that helps, @billbitt would need to look into the db to possibly reset your password.

**Comment by ceoger** [comment]
yes @tzarebczan I signed up through the main spee.ch site 
![spech](https://user-images.githubusercontent.com/38915222/39788094-381a0ee0-5318-11e8-8fdb-eddda7debdd0.JPG)

**Comment by alyssaoc** [comment]
login issues should be resolved, reopen if necessary
