### ISSUE TITLE
update spee.ch-components to use aliased paths

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#443]
all of the React imports need to be updated to use `@pages/` `@containers/` or `@components`

**Comment by billbitt** [comment]
@ykris45 if you want to handle this one, I can provide you some details on how to complete it.  Shouldn't be to hard.

**Comment by ykris45** [comment]
@billbitt okay i will try to take this stab my friends

**Comment by ykris45** [comment]
send details on ykristianto500@gmail.com guys.

**Comment by billbitt** [comment]
Issue moved to [lbryio/spee.ch-components #8](https://github.com/lbryio/spee.ch-components/issues/8) via [**ZenHub**](https://www.zenhub.com/)
