### ISSUE TITLE
spee.ch homepage missing og:image meta tag 

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#447]
Example of how this makes social links look bad: https://twitter.com/spee_ch/status/996421715575091200

**Comment by jsigwart** [comment]
This is still an issue. We should at least put the speed.ch logo card for the https://spee.ch go:image tag. Here's a screenshot of what open graph tags are seen, and how the link is viewed on Twitter.

<img width="1015" alt="screen shot 2018-06-11 at 11 06 19 pm" src="https://user-images.githubusercontent.com/1363664/41273027-9662fd8a-6dcc-11e8-8ce3-f9b4949572eb.png">
<img width="622" alt="screen shot 2018-06-11 at 11 03 07 pm" src="https://user-images.githubusercontent.com/1363664/41273028-968b1c20-6dcc-11e8-8778-ccdf6acc15e5.png">

**Comment by billbitt** [comment]
FYI, this is fixed in master.  I’ll leave open until it is live on the site.
