### ISSUE TITLE
Post URL input box size should be dynamically adjusted

### ISSUE THREAD

**Issue by delta1512** [lbryio/spee.ch#462]
I was recommended to post this issue here. 

On the spee.ch site after inputting an image, you are presented with the option of setting your own URL and I couldn't help but realise the input box (red) was not the full length as the bar indicates as shown in green:

![](https://i.imgur.com/vXBbUns.png)

Here is a gif of the problem while entering a URL:

![](https://i.imgur.com/RC2t3Ba.gif)

This was originally experienced on Arch Linux using Firefox Quantum 60.0.1 and can be reproduced in my Vivaldi browser too. I would get my web-dev friend to do a PR but unfortunately he isn't available.

**Comment by Aurailus** [comment]
```input#claim-name-input {
    width: calc(100% - 170px);
}```
Hey, I'm @delta1512's web dev friend he was mentioning. Above is the code snippet you need to fix your problem. I would make a push but I can't find where your stylesheet is. Either it's not in this repo or it's in some strange format I don't understand. Anyway, hope it helps :)

**Comment by tzarebczan** [comment]
@Aurailus Thanks for taking a look at this. I replied to you on Discord. You should be able to find what you are looking for here: https://github.com/lbryio/www.spee.ch

**Comment by billbitt** [comment]
This issue should be fixed with the scss update using flexboxes.  @Aurailus @delta1512, the style sheets are now located in `/client/scss/`
