### ISSUE TITLE
publish in a channel does not show up immediately

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#479]
If a publish is made into a channel, it does not show up until the client refreshes the app.  I believe this is because the redux store already retrieved the channel's info, including the list of claims, so it is not making a new request.  After a successful publish, the asset record needs to be added to the channel's claims array or else the channel's info needs to be refreshed in full.

**Comment by kauffj** [comment]
@billbitt should this be tagged Osprey? Not sure how important this is

**Comment by tzarebczan** [comment]
@skhameneh this is the issue I mentioned and it's still happening. It may be important to fix for Osprey.

**Comment by kauffj** [comment]
If new publishes don't show up without hitting reload, this probably should be fixed for Osprey.

**Comment by tzarebczan** [comment]
Looks like it doesn't get added until it's confirmed + refreshed.

**Comment by tiger5226** [comment]
@daovist Chainquery has been updated to process mempool transactions. It regularly checks for these every second and processes them. See https://github.com/lbryio/chainquery/issues/59 for added details.

**Comment by daovist** [comment]
Excellent! Thank you @tiger5226

**Comment by skhameneh** [comment]
During testing this gave a very acceptable update time (few seconds); we will actively work on improving times.  Closing for now.
