### ISSUE TITLE
Simplify homepage

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#48]
Strip out the non-essential info from the homepage and move it to a subpage.

**Comment by billbitt** [comment]
also: call out the open-source nature of this project on the homepage and encourage forks/contributions

**Comment by lyoshenka** [comment]
:+1: 

post some screenshots of the finished homepage? show off your work :-)

**Comment by billbitt** [comment]
@lyoshenka ;) 
Nothing major, but another step in the right direction.  We moved all the 'about' type content to a separate page.  The goal is to streamline the homepage and get users to the publish tool without any unnecessary noise.  Below are screen grabs of new slimmer and 'about' page.  More content will be added to the homepage over time.

![screenshot 2017-07-03 19 16 54](https://user-images.githubusercontent.com/19243959/27813326-f9ae89ce-6029-11e7-8ebb-f6ba4d3f7938.png)

![screenshot 2017-07-03 19 57 15](https://user-images.githubusercontent.com/19243959/27813325-f9adebd6-6029-11e7-95ab-056987e76176.png)
