### ISSUE TITLE
Unable to zoom in on images.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/spee.ch#486]
When I open an image in a new tab, I cannot zoom in on the image.
For e.g.: https://spee.ch/62166280beb4f086cf419191c4297650deb79294/TotW-NYC.jpeg
When I go here, the image is much higher resolution that my monitor, so I would like to zoom in and see the finer details. Please let me know if more clarification is required.

Running on Chrome in Ubuntu 18.04.

**Comment by tzarebczan** [comment]
Similar to https://github.com/lbryio/spee.ch-components/issues/1

**Comment by hackrush01** [comment]
Closed. Already filed at lbryio/spee.ch-components#1
