### ISSUE TITLE
npm ERR! 404 'spee.ch' is not in the npm registry.

### ISSUE THREAD

**Issue by scriptzteam** [lbryio/spee.ch#488]
npm ERR! 404 'spee.ch' is not in the npm registry.

**Comment by tzarebczan** [comment]
Please follow these instructions if you want to setup a speech clone: https://github.com/lbryio/www.spee.ch/blob/master/quickstart.md

**Comment by billbitt** [comment]
thanks @scriptzteam for reporting.  Can you provide steps to reproduce?

**Comment by billbitt** [comment]
closing as we are not planning to add the spee.ch repo to the npm registry at the moment.
