### ISSUE TITLE
Block publishing on existing name published by spee.ch

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#49]
At least until the daemon supports multiple publishes to the same name.

**Comment by billbitt** [comment]
I believe the solution is simply to check the mysql table for whether that claim name is present before issuing a publish.  However, the table contains both files published by speech and files merely retrieved through speech (published via the app or elsewhere).  We only want to disallow publishes made from spee.ch specifically.  We likely need another field in the spee.ch table to track this.  I think a `claim address` field would be best, so spee.ch can just search for the name and then compare the claim address to it's own claim address(es). 

There is a potential race condition to be aware of.  For user experience, it would be best to check the eligibility of the name immediately upon it being entered into the input field.  However this could create a race condition as there will be a slight gap from when the check is made to when the file is actually uploaded and the publish request is sent to the daemon.  If the race condition becomes an issue, the solution would be to check twice: once when the input field changes in the client, and again when the publish is initiated.

**Comment by billbitt** [comment]
Card updates per SCRUM meeting:
- user story:  As a user, I want my URLs to be permanent so that I can access them in the future without fear that they have been overwritten by another claim.
