### ISSUE TITLE
No video with supported format and mime type found

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#497]
Not sure what's going on for this claim: https://spee.ch/e63586721f1943e64b29eac14cff17adae4ada99/lbry 

@billbitt said "it's making a video tag, but it's not adding a source, just showing the poster"

**Comment by tzarebczan** [comment]
This is working now, but only after the file was accessed by going to https://spee.ch/e6/lbry.mp4 first.

**Comment by tzarebczan** [comment]
Here's another: https://spee.ch/42581c1f62ca971f39f6792eef8c1c8f05ad30e5/on-the-river-test-panning-down-stream

**Comment by tzarebczan** [comment]
Not sure if this is similar, but ran into it recently: https://spee.ch/thesecondhandmarchingband-ahurricaneathunderstormtheyshootmuisc-1

**Comment by billbitt** [comment]
Closing, as I believe this was a result of cloudflare caching issues and is now fixed.
