### ISSUE TITLE
some publishes only have 'blob' for the file name

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#502]
some publishes only have 'blob' for the file name, for example:

`Successfully published QA71imlNV9nUf2i67cxiGlUF blob`
`claim_id: 'cef75fb4c62391900d7c9bf211ac944c652e603c'`

I believe these are coming from the app, but not sure if issue is app side or spee.ch's side.

**Comment by tzarebczan** [comment]
These are still coming in. When trying to upload a file without an extension through the app/api, you get "upload failed" - so not sure how these are getting through.

**Comment by billbitt** [comment]
closing because I think https://github.com/lbryio/spee.ch/issues/507 encompasses this issue
