### ISSUE TITLE
app thumbnail uploads result in broken links on spee.ch

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#507]
@billbitt commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67)

for thumbnail publishes made via the app (from macs?), the thumbnail link appears or is broken on spee.ch.

steps to reproduce:
1. open the LBRY app
2. go to publish and select a video
3. select an image to upload for the thumbnail
4. when the thumbnail is done being published, click the 'view on spee.ch' link
5. the page will show a broken image and display the img alt instead of the image

expected outcome:
1. when clicking the 'view on spee.ch' link, the asset should be displayed on the page.

example: https://spee.ch/4b1567a9015c5d97739970213346bb516a2219a6/rBtfkpiLmVMrUqxTNYcHOe4z.png

notes:
- the images do seem to unfurl in slack.  i.e. they appear to be served properly to slack
- the image is (sometimes?) served properly to the app after the video is published.  It seems this has varied, and in some trials the thumbnails show, while in others they do not.
- this issue does not seem to happen for .jpg files, but only for .gif and .png

---

@billbitt commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67#issuecomment-402213863)

@tzarebczan @seanyesmunt fyi

---

@billbitt commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67#issuecomment-402214319)

I'm thinking this has to do with the publish route's middleware parsing the formdata from the publish request.  Perhaps starting the publish before it has all of the file, or something like that.

---

@billbitt commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67#issuecomment-402215029)

@tzarebczan do you have an example uri for a video that was published from the app and _did_ work correctly? I'd like to compare.  Otherwise, I'll do a test upload from my app.

---

@tzarebczan commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67#issuecomment-402217422)

Here's a JPG that worked: https://spee.ch/37cd0ab1b52b55b4eb04849fb9f6769c51180184/kCutEbo5xJeeOZLJOPHBVmQT.jpg

---

@billbitt commented on [Tue Jul 03 2018](https://github.com/lbryio/grooming/issues/67#issuecomment-402227378)

ugh, I meant to make this issue on `lbryio/spee.ch` not `lbryi/grooming`

**Comment by billbitt** [comment]
I'd like to see if attaching the file to the form data as a File rather than a Blob has any impact.  I made a branch here:

If the issue continues, the next step would be to see if there is something going on with Blobs/Files created by Macs (assuming the issue is still located there) and the middleware being used to read the form data: https://www.npmjs.com/package/connect-multiparty.

The next step after that would be to see if there is something with how spee.ch is storing and accessing the file data (like the path), however I doubt that would be an issue if there isn't something else happening upstream.

Lastly, it is possible the file is being uploaded and published successfully but then deleted after the publish is complete.  That could explain why spee.ch has the file records and published successfully, but then was not able to find the file to serve it.  It could also explain why the file showed up later, if something triggered spee.ch to redownload the file.  I would like to look at a specific case of a file that did not appear immediately but then did later.

**Comment by billbitt** [comment]
will do @kauffj.  I've updated the comments above.  At first we thought this was correlated to uploads coming from macs or certain file types, which is why I thought it might be related to the upload process, the middleware processing the uploaded file, or the lbry publishing.  However, this seems to happen across windows & mac, and seems to happen to all file types except jpg.  The files do seem to publish successfully and store on the spee.ch server successfully, so I think this is a much simpler issue that has to do with spee.ch and the serving or displaying of the files.  I've got a couple ideas, but will circle back with @skhameneh if I can't solve quickly.

**Comment by billbitt** [comment]
@kauffj @skhameneh one issue that I am having is that I cannot seem to reproduce the bug when pointing my lbry app to publish via dev1.spee.ch or staging.spee.ch.  When I do so, I can view the images without error.  This should be a clue, but I'm having trouble figuring out what it means.  The servers are running the same spee.ch code, the differences (that come immediately to mind) would be their lbry wallet or the presence of cloudflare on production.  I am not sure how any of those differences would explain this issue, however.

On the other hand, I did narrow down where the bug is occurring on production.

After publishing on production, the file displays fine while viewing from the a shortened direct url (`https://spee.ch/7/webapp-png-test.png`) or the long details url (`https://spee.ch/734f5cb226f7b3796e304c255bfe44d3ccae5aa2/webapp-png-test`).

![screenshot 2018-07-07 15 38 03](https://user-images.githubusercontent.com/19243959/42415298-712e136a-81fe-11e8-88c0-f55270671de3.png)

However, once I visit the long direct url, the link breaks for subsequent visits, including the short urls: https://spee.ch/1b99322abcfbf0484582637df20455fce74702c6/webapp-png-test-3.png

![screenshot 2018-07-07 15 50 22](https://user-images.githubusercontent.com/19243959/42415288-2a4dc8e6-81fe-11e8-912d-41ca4c007ace.png)

https://spee.ch/1/webapp-png-test-3.png

![screenshot 2018-07-07 15 47 54](https://user-images.githubusercontent.com/19243959/42415286-0f6109d0-81fe-11e8-85e7-694765c85522.png)

This explains why they are immediately showing as broken from the app, because the app takes the user directly to the long direct url.

Conclusion:
It appears that visiting the long, direct url is what triggers the error and stops spee.ch from subsequently serving the asset to any of the urls that display the asset.  So far, this only happens on production, and not on dev1.spee.ch or staging.spee.ch.  I am not sure what is causing this yet, but perhaps I could do some live debugging with @skhameneh next week.  If either of you have any thoughts DM me or leave them here.

**Comment by kauffj** [comment]
It appears that the URL for the embedded image is returning a full HTML resource rather than just the image.

![screenshot from 2018-07-09 10-37-39](https://user-images.githubusercontent.com/530774/42456950-23fbb798-8364-11e8-93ab-7ad9e5263321.png)

**Comment by kauffj** [comment]
(Deleted incorrect comment.)

1) Is the file still on disk?
2) Don't be afraid to debug in production if production is broken and the only place a bug is happening.
3) When you figure out what is causing the environment difference, make sure to fix that as well.

**Comment by billbitt** [comment]
Debugged this this morning with @kauffj and @skhameneh.  It seems this was a result of cloud-flare serving an html document instead of an image or video for the long url direct link.  This is a result of using one url for two purposes.
