### ISSUE TITLE
Why fee, how do i have to pay

### ISSUE THREAD

**Issue by yashwanth2804** [lbryio/spee.ch#523]
after running curl publish command i got 

`{"success":true,"message":"publish completed successfully","data":{"name":"enc","claimId":"04a53c51daa816c02dfb6a465680ffea3f8a9401","url":"https://spee.ch/04a53c51daa816c02dfb6a465680ffea3f8a9401/enc","lbryTx":{"claim_address":"bQ888BYonEWnRXfPMCrN4fjMcx74UNrZfU","claim_id":"04a53c51daa816c02dfb6a465680ffea3f8a9401","fee":0.006,"nout":0,"tx":"01000000017d0543c3518e9de4113d9f7831bef6c4bc778ee870aebad6eb70862dc4794929010000006a473044022039b7efae38e1ca90874fe2c174d8816d38d1d827250c0916c0bc539ca65d727002200f43634bdc572a2aef2630492f3d96d54c00f1c664137c5047b8c8e1d7d125a901210308af85d8e632c052001dc9600c90dbe7be8a2539f3fa2e26cd699364a58c4822ffffffff0240420f00000000008fb503656e634c6d080110011a670801121f080410011a03656e6322002a07537065652e636832012038004a0052005a001a42080110011a30c3fffef3359a57b9883646be242e88780840572db2b13bf5488b94ee9803aeaf65175eff410021d3f62a9bfc7073b298220a696d6167652f6a7065676d7576a9147cfbcc0abbd12c538801840487defc02b90a309e88acc0894601000000001976a91470fa90105452fba5e982f55e6f4c43eca7e60a7888ac00000000","txid":"0dc99b6344d1cfb8d14d753e2a1bd8e10ade90ca0cbdd32c77d5f6f0ce2b31d5","value":"080110011a670801121f080410011a03656e6322002a07537065652e636832012038004a0052005a001a42080110011a30c3fffef3359a57b9883646be242e88780840572db2b13bf5488b94ee9803aeaf65175eff410021d3f62a9bfc7073b298220a696d6167652f6a706567"}}}`

**,"fee":0.006,"**

what exactly is the fee means, if i am going to publish from curl as anonymous why do i have to pay if so,
how long the image gona stay in live 

thanks in advance

**Comment by tzarebczan** [comment]
The LBRY network requires a deposit along with a transaction fee to create an entry in the blockchain to store metadata for the upload. The fee portion is the transaction fee - this varies with how long the name of the claim is (this may change in the future, but there will still be a small fee).

So you aren't actually paying the fee, spee.ch/LBRY Inc is.

Learn more: https://lbry.io/what
https://lbry.io/faq/what-is-lbry

**Comment by yashwanth2804** [comment]
Thank you ,
is there any javascript api implemetation of _crul_ **publish**  images

**Comment by tzarebczan** [comment]
I see you posted another issue with that question, closing this one.
