### ISSUE TITLE
add height and width columns to File table records

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#527]
Story: As a developer, I want to be able to know an asset's height and width so that I can use those dimensions to display the asset properly on spee.ch and to set the preview aspect ratio on social sharing cards for twitter.

**Comment by billbitt** [comment]
this will be very helpful for social sharing cards as well as displaying the asset properly on spee.ch

**Comment by billbitt** [comment]
Note: Are there any points in the code where height and width of the asset would be needed, but spee.ch only has the Claim info and no File record has been created yet?

**Comment by skhameneh** [comment]
Note: We talked about reading metadata is possible rather than having to parse the entire image file (or any frames for video).  IIRC nearly all formats provide the size within meta

**Comment by billbitt** [comment]
@skhameneh got it, but we still need to start the file download and get the image metadata from the file itself, as opposed to getting that info from the lbry claim.  Correct?

**Comment by kauffj** [comment]
I'd pretty strongly recommend using imagemagick for this. It's well supported and heavily used and will handle all kinds of corner cases that a hand rolled solution will not.

It's also decently likely that at some point we'll want to perform optimizations, compression, strip certain metadata, and/or do other asset processing and ImageMagick will facilitate all of this.

**Comment by billbitt** [comment]
@kauffj @skhameneh see PR #543.  I ended up going with:
- [image-size](https://github.com/image-size/image-size) to get dimensions of images
- [get-video-dimensions](https://www.npmjs.com/package/get-video-dimensions) + `ffmpeg` to get dimensions of video. 

I did add `imagemagick` to the dependencies because I think we will need to use it in the future when we want to resize or otherwise manipulate the images themselves, but [the npm packages that wrap imagemagick cli](https://www.npmjs.com/package/imagemagick) have not been supported for many years and I ran into bugs trying to use it to get height and width.  On the other hand,  [image-size](https://github.com/image-size/image-size) is very well supported (updated a month ago) and tested (1.4 million weekly downloads) and worked very well on all images I tested.

**Comment by kauffj** [comment]
I don't think it makes sense to add a dependency that the code isn't actually using.

If you look at using imagemagick again, I would recommend just calling imagemagick directly. The npm package you linked adds very little value and possibly subtracts value since it requires you to learn both their API AND the imagemagick API (after all, that's the API you're ultimately calling and need to know the function/parameter names of).

**Comment by billbitt** [comment]
Removed imagemagick npm package: https://github.com/lbryio/spee.ch/pull/550
