### ISSUE TITLE
images are expanding to 100% without maintaining aspect ratio

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#528]
Story: As a user, I want my images to maintain their aspect ratio everywhere they are displayed on the site so that they look nice when I view or share them.

Issue: images are being stretched to 100% of the parent div, but not maintaining aspect ratio.

the image seems to be inheriting the 100% width from the Column layout component that it is nested inside.

https://dev1.spee.ch/8de38150bea952301dcc178f33d5e9d1b85f13bd/typingcat

![screenshot 2018-07-16 10 53 13](https://user-images.githubusercontent.com/19243959/42775336-f847b892-88e8-11e8-95e0-5da791f5e081.png)

Expected behavior: images should either remain smaller than 100% width at normal aspect ratio or being expanded while maintaining aspect ratio.

**Comment by NetOperatorWibby** [comment]
On the `<img/>` tag:

```css
width: 100%; height: 100%;

object-fit: contain;
object-position: center;
```
