### ISSUE TITLE
Implement "app download" twitter card when mobile app is ready

### ISSUE THREAD

**Issue by Feanor78** [lbryio/spee.ch#535]
Details here:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/app-card

**Comment by billbitt** [comment]
great suggestion @Feanor78 !

**Comment by kauffj** [comment]
Isn't this for lbry.io?

**Comment by billbitt** [comment]
that would make more sense.  I assumed this was just a result of the business team wanting to expand where the lbry app download messaging was being placed, like the discussions about having the app download link on the spee.ch show pages.

**Comment by billbitt** [comment]
Issue moved to [lbryio/lbry.io #685](https://github.com/lbryio/lbry.io/issues/685) via [**ZenHub**](https://www.zenhub.com/)
