### ISSUE TITLE
Landscape image shows preview in portrait mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#540]
Spee.ch URL: https://spee.ch/0/Lbry-c-swag

Twitter post: https://twitter.com/TomZarebczan/status/1020349594293719041?s=19

It also did this on FB and Discord. Slack somehow unfurled correctly. 

This image was taken in landscape mode mode on a Samsung Galaxy S8+ via the default camera app.

**Comment by jessopb** [comment]
duplicate of https://github.com/lbryio/spee.ch/issues/435: exif image orientation data.
