### ISSUE TITLE
Clicking back from DMCA page does not take you back

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#548]
Ran into this today:

1) Click on https://spee.ch/@FransNFNRoses:1ff8b739ba27392d025f7fb58f94e7ea802c6ab3

2) Click the first first tile

3) Notice the DMCA message, now click Back on your browser

4) The URL updates, but the page does not

**Comment by mburstiner** [comment]
Light lift, it's on our radar!

**Comment by jessopb** [comment]
If dmca'd content is not linked from preview page, there's no back to go to.
