### ISSUE TITLE
Track and show view counts to publishers

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#553]
If spee.ch knows that I created the content (presumably authenticated as the channel), it ought to show me the view count.

**Comment by billbitt** [comment]
note: we discussed adding a 'views' column to the File table

**Comment by skhameneh** [comment]
Required for https://github.com/lbryio/spee.ch/issues/556, working on this.

**Comment by jessopb** [comment]
Is it still preferable to only show views to logged in channel owners?
