### ISSUE TITLE
Ability to show trending content as the homepage (and/or homepage configuration)

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#556]
If:

- The trending code still exists and is functional
- The homepage can be overridden in a local install

Then this ticket is already completed. Otherwise, we want certain spee.ch installs to be able to show different homepages.

**Comment by skhameneh** [comment]
I'm working on an implementation that allows rendering components (containers) such as `ChannelClaimsDisplay` without relying on the a single reference to a channel within the active requests state.

**Comment by tzarebczan** [comment]
Soemthing to keep in mind: we'll get lots of hits from LBRY app thumbnails... Are those easy to identify and filter out?

**Comment by kauffj** [comment]
@NetOperatorWibby I'd like you to participate in the design/implementation of this page once @skhameneh has made some progress.

**Comment by kauffj** [comment]
Per discussion with client, let's make sure we retain the ability to sort by trending or strictly by date.
