### ISSUE TITLE
notNull Violation with File record

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#559]
getting the following error: 

```
notNull Violation: File.name cannot be null, notNull Violation: File.claimId cannot be null, notNull Violation: File.outpoint cannot be null, notNull Violation: File.fileHeight cannot be null, notNull Violation: File.fileWidth cannot be null, notNull Violation: File.fileName cannot be null, notNull Violation: File.filePath cannot be null
```
on:

https://spee.ch/4b9997473c3b63c6fdbbdacef043671b9a6d5c5c/moonlighter-review-secret-of-the-5th

likely related to creation of File record, perhaps related to migration of File table

**Comment by billbitt** [comment]
@tzarebczan fyi

**Comment by tzarebczan** [comment]
Happening on images too:https://spee.ch/0a45ad1b7f7ef6c6507d219d98f61c8beea77076/testthumbupload

Looks like this affects any previously unviewed claim on spee.ch .
