### ISSUE TITLE
implement continuous integration between this repo and spee.ch server.

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#57]
Story: As a developer, I want to be able to commit my changes to master and have those changes go live, so that I do not have to spend time manually updating the version on the server.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by skhameneh** [comment]
@alyssaoc yes and we very much want this, it'll help a lot with maintaining updates

**Comment by skhameneh** [comment]
We have auto deploy but not integration, @nikooo777 wanted to use autodeploy.
Out of necessity that's all that has been implemented.

**Comment by nikooo777** [comment]
for CI we need a set of running tests or a working build flow.
I spent a good chunk of my saturday trying to figure out a clean solution. I have a branch up that almost builds on travis. As soon as you guys figure out the `npm run configure` part and a way to get `npm run build` to run without the configs I'll gladly change the auto-deployment to CI.
