### ISSUE TITLE
Add Terms of Service to spee.ch

### ISSUE THREAD

**Issue by jsigwart** [lbryio/spee.ch#571]
Per discussion on https://github.com/lbryio/lbry.io/issues/430 we need to have a Terms of Service document for spee.ch.

**Comment by heymattsokol** [comment]
I'm no lawyer, but I can probably figure out the relevant stuff to create a ToS for Spee.ch. Do you want me to tackle this one?

**Comment by finer9** [comment]
@jsigwart I'm trying to figure out what to do here.  Do we think the ToS for spee.ch would be very different than the ToS we have for the app?  Do we think I should borrow one from another image sharing site?  any help appreciated.

**Comment by finer9** [comment]
[termsfeed-html-terms-service.zip](https://github.com/lbryio/spee.ch/files/2416796/termsfeed-html-terms-service.zip)
[termsfeed-text-terms-service.zip](https://github.com/lbryio/spee.ch/files/2416797/termsfeed-text-terms-service.zip)
Please use the attached as a ToS for Spee.ch.  We'll add/edit as necessary.  I have attached an HTML and text version both.

**Comment by finer9** [comment]
@alyssaoc Who can put this live on the site please?
