### ISSUE TITLE
Enable .svg and Adobe file extentsion uploading to spee.ch

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/spee.ch#572]
The .svg file type is the most common vector graphic file type so it's important that we add the option to upload .svg files to spee.ch, in addition to .ai and potentially .psd and other Adobe file extensions as soon as possible. 

That being said, .svg is more urgent than the Adobe extensions.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
Supporting publishing of .ai files is quite different from svg. .ai are application/postscript and speech is largely hardcoded for image and mp4.
- [x] publishing shows a detailed thumbnail (+preferably a descriptive one)
- [x] publishing validates size on both client and server and reports errors
- [x] settings supplies size limit settings for application media type and/or custom file types
- [ ] * a list of default file thumbnails per contentType would be great, or at least per mediaType (text, image, etc)
- [ ] at least for non-image types, a thumbnail file chooser/generator, also #622, #599

**Comment by tzarebczan** [comment]
@jessopb to separate out into separate issues.
