### ISSUE TITLE
API authentication tokens and API restrictions

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#574]
Currently, the spee.ch API is effectively open.

As part of the Osprey project, it will be necessary to restrict API access via an authentication scheme.

Essentially, this means the ability to turn off the API for unauthenticated users and the ability to submit a token with a request that would perform the action as the appropriate authenticated user.

**Comment by daovist** [comment]
this was covered by #605 as well as UI implications of restrictions
