### ISSUE TITLE
meme generator

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#58]
add a meme generator, based off of the publish tool, as its own page.

**Comment by skhameneh** [comment]
Would be great to have, @NetOperatorWibby has developed something similar for .tech

**Comment by alyssaoc** [comment]
@NetOperatorWibby How "sharable" do you think your meme generator code is?

**Comment by NetOperatorWibby** [comment]
As-is, not very. It'd have to be converted into a plugin.
