### ISSUE TITLE
Better indication that content is still downloading (page looks broken on first access)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#585]
When accessing content that was uploaded from LBRY on spee.ch for the first time, the video looks like it's broken because playback does not start immediately during download (I could have sworn it used to, maybe something broke here recently). If you refresh the page and the download has completed, it will then play. 

![image](https://user-images.githubusercontent.com/8120721/44413409-45f1e600-a539-11e8-81fe-e1ddf950a936.png)

**Comment by skhameneh** [comment]
Fix included with https://github.com/lbryio/spee.ch/issues/593
