### ISSUE TITLE
Claim page shows broken image when accessed the first time

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#588]
This could be related to ffmpeg changes. When accessing an image or gif on spee.ch for the first time (i.e a user uploading their own content and then viewing on the web, or a user accessing something that hasn't been loaded on spee.ch), the page looks like it's broken. Refreshing the page does not help, as it cached (not even in incognito or another browser). 

![image](https://user-images.githubusercontent.com/8120721/44702036-66510180-aa5f-11e8-8bf2-05f55fc8ded6.png)

**Comment by skhameneh** [comment]
Will need to:

1. Change cache headers for content not found (for Cloudflare, pages should respond with a few seconds timeout at most - or no cache at all): https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache-
2. Spee.ch pages should not attempt to load content that is not available until it is fully loaded and ready to render.

**Comment by skhameneh** [comment]
Relates to https://github.com/lbryio/spee.ch/issues/585

**Comment by skhameneh** [comment]
Fix included with https://github.com/lbryio/spee.ch/issues/593

See the fix here: https://github.com/lbryio/spee.ch/pull/593/files#diff-f29593834f46e73e4247a708ad7434e3R39
