### ISSUE TITLE
serve multiple image sizes

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#60]
If client indicates the size of the image requested, provide the asset in that size.

Examples:

- if client requests `spee.ch/example/h40`, spee.ch serves an image with height of 40 (while maintaining aspect ratio)
- if client requests `spee.ch/example/w60`, spee.ch serves an image with width of 60 (while maintaining aspect ratio)
- if client requests `spee.ch/example/40x60`, spee.ch serves an image with height of 40 and width of 60 (stretching original image)

**Comment by MSFTserver** [comment]
http://viralpatel.net/blogs/resize-image-dynamically-php/

**Comment by skhameneh** [comment]
Will require selectively caching resized images; this is useful but should be low priority considering complexity.

**Comment by jessopb** [comment]
closing. #749 addressed in pr
