### ISSUE TITLE
image unfurl issue on Discord (+others?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#601]
Not sure if this is an issue exclusive to discord or if it's related to sizing properties. I know @Invariant-Change looked into something similar at one point and noticed we were missing some tags. 

Link: https://spee.ch/8/Screenshot20180917-174120

Discord:
![image](https://user-images.githubusercontent.com/8120721/45636975-508b9680-ba77-11e8-880c-c3322e5b007b.png)

Slack:
![image](https://user-images.githubusercontent.com/8120721/45637028-7022bf00-ba77-11e8-82b7-93481288637f.png)

**Comment by Invariant-Change** [comment]
Spee.ch is still missing the HTML `height="value"` and `width="value"` parameters. Without these, many applications don't know how to deal with images when embedding.

There are also performance and SEO implications.

I will see if I can fix this. It's an area of Speech I was playing around with a few months ago.

![image](https://user-images.githubusercontent.com/29914179/45698500-80d45180-bbab-11e8-8194-fd46b68ac4e8.png)

**Comment by skhameneh** [comment]
Looks like the fallback size is used here:
https://github.com/lbryio/spee.ch/blob/412d7cafb46e72347f59032a4b7d0155b8723776/server/controllers/api/oEmbed/getOEmbedDataForAsset.js#L58

**Comment by Invariant-Change** [comment]
Yeah, looks like multiple issues going on at once. OG, defaults and Discord image height and width are all wrong. I'm pretty sure with the HTML values being served, this will be fixed?

I know that in the first version of speech this looked like an easy fix, by adding the height and width HTML properties dynamically, but I'm not so sure for the new version. I've not had enough time to explore it.

![image](https://user-images.githubusercontent.com/29914179/51811775-4c5f6780-22fa-11e9-9ccc-52a9d6e8fe9a.png)

**Comment by skhameneh** [comment]
@Invariant-Change see the PR attached, I'll close this issue.  It can be re-opened if another rendering issue comes up.

**Comment by Invariant-Change** [comment]
I think these are the variable that needs to be passed to the OG and HTML data dynamically. It's not something I've looked in to since last year, but maybe something @jessopb can explore if any issues continue after the PR? Bill was using [handlebars.js](https://handlebarsjs.com/) to pass these variables.

[getMediaDimensions](https://github.com/lbryio/spee.ch/blob/master/server/utils/getMediaDimensions.js)

```
fileHeight
filewidth
```
