### ISSUE TITLE
Osprey Landing Page

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/spee.ch#603]
This is the channel page for our partner, Osprey. The code for this will be sent manually to Travis instead of committed to this repo directly.

**Comment by NetOperatorWibby** [comment]
Travis is working on this.

**Comment by NetOperatorWibby** [comment]
Also, since it will likely get redesigned _anyway_ as spee.ch gains more capabilities it doesn't matter who creates the first one (or 15).

**Comment by kauffj** [comment]
There's still work to be done on this. Details to come via Slack.

**Comment by kauffj** [comment]
- Hide nonsense channel info
- About page copy
- Titles under the cards
- Slogan
- Anything else that you can find that seems wrong
