### ISSUE TITLE
thumbnail missing temporarily during video + thumb upload

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#604]
I uploaded https://spee.ch/2ba88daefcc5cacc9a5068bdc4e468fe50397ae4/test-video-with-thumb and when it took me to the page, the thumb was missing. When I accessed the thumb directly, it said a claim could not be found at https://spee.ch/@thumbnails:e7b0620f6e5a56031cbfc8b9373b02d6ed63c39c/test-video-with-thumb-thumb.png. I then refreshed a minute or two later, and it showed up.  Maybe the thumb uploads are not being added to the database? 

![image](https://user-images.githubusercontent.com/8120721/45766304-397aaf00-bc05-11e8-9e26-2ee58d5e421e.png)

**Comment by tzarebczan** [comment]
When I tried this on dev1, this also happened: 
![image](https://user-images.githubusercontent.com/8120721/46098620-d8b61e00-c192-11e8-97c5-76f3fc429580.png)

https://dev1.spee.ch/a13cd5cd3de68007feef28c510a5f2890bb29316/speechdevtest - thumb never showed up either (not sure if same or different issue)

**Comment by kauffj** [comment]
This is probably just #479 but @daovist will confirm

**Comment by alyssaoc** [comment]
this has been fixed, closing
