### ISSUE TITLE
Social sharing options on decentralized platforms

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#608]
A feature request from a LBRY user: options to share on decentralized social networks like Mastodon, Diaspora and/or Friendica

Current share options: 
twitter facebook tumblr reddit

**Comment by stragu** [comment]
This stats website is a good place to have a look at what federated decentralised social networks are the most popular: https://the-federation.info/
Not all of them would allow for simply sharing a link to something, but the obvious ones would be: [Mastodon](https://joinmastodon.org/), [Diaspora](https://diasporafoundation.org/), [Pleroma](https://pleroma.social/), [Friendica](https://friendi.ca/) and [Hubzilla](https://project.hubzilla.org/page/hubzilla/hubzilla-project).

Outside the Fediverse, [Movim](https://movim.eu/) is another social network based on XMPP.

When it comes to distributed communication means (as opposed to Telegram / WhatsApp etc.), I don't know how applicable it would be, but [Matrix](https://matrix.org/blog/home/) and [Tox](https://tox.chat/) could be good ones.

But for all those, I guess the feasibility depends on if browsers recognise certain kinds of links and can redirect to the right app (like they would for `mailto` or rss links), or if the social network has a hosted sharing tool, like [Diaspora](https://share.diasporafoundation.org/about.html).

Obviously, I am not expecting to see all of them in there. I am just trying to give ideas and pointers! :+1:

**Comment by Katamori** [comment]
Also [Steem.](https://steemit.com)
