### ISSUE TITLE
Blockchain hard fork testing

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/spee.ch#618]
## The Issue

With the blockchain upstream and normalization changes in the upcoming hard fork, 
as spee.ch developer, 
I want to identify as many automated and manual tests as possible so that the hard fork does not break spee.ch.

## DOD/Acceptance Criteria
Identify all interactions with the blockchain and document
Identify and document possible testing scenarios for those interactions

As a goal, we should build a test environment for repeatable testing of future changes

**Comment by kauffj** [comment]
The regular expressions here will become invalid: https://github.com/lbryio/spee.ch/blob/master/utils/lbryUri.js

Please look at where the associated functions are used for clues as to what the fork might affect.

Please file separate tickets for any spee.ch changes that will need to happen after the fork.

**Comment by skhameneh** [comment]
Will be following up:
https://github.com/lbryio/lbrycrd/issues/208#issuecomment-444212905

Currently I don't see many breaking changes unless characters we treat as reserved will cause issues.
We may need to normalize the local claims table for pending claims.
