### ISSUE TITLE
do not clear metadata with new photo

### ISSUE THREAD

**Issue by daovist** [lbryio/spee.ch#620]
If you drop a photo, then update some metadata e.g. title, then drop a new photo, it will clear the metadata due to the current behavior of [actions.FILE_SELECTED](https://github.com/lbryio/spee.ch/blob/master/client/src/reducers/publish.js#L51):

```
    case actions.FILE_SELECTED:
      return Object.assign({}, initialState, {  // note: clears to initial state
        file: action.data,
      });
```

**Comment by evanlihou** [comment]
That seems like the correct behavior to me? I'd imagine people would more often want the metadata cleared than they would want it preserved when changing the image.

**Comment by daovist** [comment]
It's claim metadata, not image metadata. I don't think a user will want to clear the title and description when changing the file.

**Comment by jessopb** [comment]
The code currently checks to see if it's update rather than just setting initialState. Closing.
```
case actions.FILE_SELECTED:
      return Object.assign({}, state.isUpdate ? state : initialState, {  // note: clears to initial state
        file      : action.data,
        hasChanged: true,
      });
```
