### ISSUE TITLE
video frame size incorrect 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#627]
On newly resolved videos, the frame size looks incorrect (lengthwise). It could be related to the ffmpeg changes which calculate dimensions (maybe when it fails?)

Incorrect:
https://spee.ch/879defe928c09fd5f1ca09fe37515827eb703e27/blooper3

Correct: 
https://spee.ch/6b1436fed5e843c2c945ec0bb4600905a6c0ba0c/tt-nex

**Comment by alyssaoc** [comment]
this is a css issue

**Comment by jessopb** [comment]
https://dev2.spee.ch/@CryptoCandor:9/blooper3
and 
https://dev2.spee.ch/@CryptoCandor:9/tt-nex
players fit the content very well. The second was listed as "correct" but it's now better than it was.
