### ISSUE TITLE
Better Monitoring

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#631]
As spee.ch matures and usage increases, it's important that we notice issues promptly.

I know that a lot of failures get logged and/or sent to chat, but we should look at tools to push notifications when core functionality is broken or the server isn't responding, etc.

Want to know when sites go down
Want error messaging

**Comment by kauffj** [comment]
@lyoshenka if you have a recommended solution, please share

**Comment by eukreign** [comment]
I'd recommend sentry for tracking internal failures specifically but sentry only works with exceptions, it doesn't do uptime and higher level monitoring. https://sentry.io Sentry has a plugin for almost every programming language and development framework so it's easy to have it integrated in all of our apps and have the exceptions reported in one place. It even lets you turn reported exceptions into github issues automatically (and it will aggregate similar exceptions into a single issue).

**Comment by skhameneh** [comment]
I found we have Uptime Robot configured (was not aware and found it while ironically working on setting it up).

I'm looking into Sentry, unfortunately it's used for a lot of tracking and my own rules have it blocked. 😒

**Comment by skhameneh** [comment]
Added Cabot, investigating further improvements.
Closing for now.
