### ISSUE TITLE
OmNom: Claiming of name * failed: error: the transaction was rejected by network rules: too-long-mempool-chain

### ISSUE THREAD

**Issue by scriptzteam** [lbryio/spee.ch#633]
So whats this?

`{"status":400,"success":false,"message":"{\"error\":{\"code\":-32500,\"data\":[\"  File \\\"site-packages/twisted/internet/defer.py\\\", line 1299, in _inlineCallbacks\",\"    \",\"  File \\\"site-packages/lbrynet/core/Wallet.py\\\", line 580, in claim_name\",\"    \",\"exceptions.Exception: Claiming of name *** failed: error: the transaction was rejected by network rules.\",\"64: too-long-mempool-chain\",\"[***]\"],\"message\":\"Claiming of name *** failed: error: the transaction was rejected by network rules.\\n\\n64: too-long-mempool-chain\\n[***]\"},\"id\":null,\"jsonrpc\":\"2.0\"}"}`

**Comment by tzarebczan** [comment]
hi @scriptzteam - our server was experiencing some issues at the time but it should be fixed now.
