### ISSUE TITLE
short permanent urls for speech -> 'spee.ch/example/x'

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#65]
**Story**: As a user, I want to be given a short url, so that I can use that url to embed or link to without having to remember or copy a very long url string.

**Comment by kauffj** [comment]
1. This ticket was intended to support all partial matching. (i.e. not just one letter or forty)
1. The logic that shows the short URL can potentially conflict. Instead, spee.ch would need to determine the shortest URL that is guaranteed to return the same asset.
