### ISSUE TITLE
notify user of dmca takedown

### ISSUE THREAD

**Issue by daovist** [lbryio/spee.ch#658]
the browser lets the user know about dmca takedowns, speech just doesn't load the content

**Comment by kauffj** [comment]
how would we do this without user accounts / emails?

**Comment by tzarebczan** [comment]
This just means to display the dmca takedown page on the claim instead of a broken content image. It used to do this, something  must have broken with chainquery migration or another recent change.

**Comment by kauffj** [comment]
Got it, thanks.

**Comment by jessopb** [comment]
The solution will:
Add a configuration for customizable Takedown api server urls
Render a 451 (not found for legal reasons) error component
Load the blocked list from memory rather than from the database
Link to lbry.io/dmca
