### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by daovist** [lbryio/spee.ch#669]
Following #648 we need a system whereby changes to config, components, and style sheets make their way to deployment

Speech instances need a way to update existing config files when new options become available or necessary without editing the file manually then running `pm2 stop server` then `pm2 start server`

This is somewhat related to #660

**Comment by kauffj** [comment]
Consider just setting this up as a shell script that can be run manually or pointed as a Git post-commit hook.

**Comment by skhameneh** [comment]
Need to add deployments into TravisCI

**Comment by skhameneh** [comment]
Closing, we have auto deploy - anything specific to deploying after tests are run will need to be revisited
