### ISSUE TITLE
store sd_hash in File table

### ISSUE THREAD

**Issue by daovist** [lbryio/spee.ch#680]
If a claim file is uploaded outside of speech it will, when viewed on speech, be downloaded and stored with `name`, `claimId`, and `outpoint`. Speech needs re-download the file when it has changed. But outpoint will be updated when metadata is updated but not the file. So we should store the `sd_hash` in the File table. When it matches chainquery, serve it. When it does not match, re-download.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Related to https://github.com/lbryio/spee.ch/issues/418

**Comment by jessopb** [comment]
moving away from localdb toward chainquery and sdk, this is unnecessary.
