### ISSUE TITLE
Do not require empty folders

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#693]
Whenever possible (which is presumably always), build and configure scripts should not assume the existence of or require empty folders.

As an example, `npm run build` requires both `site` and empty subfolders within `site` to exist.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
Is it sufficient that run build checks and creates folders, or are we looking to avoid a certain antipattern in general?
