### ISSUE TITLE
Editing files: mature flag / copyright not repopulated

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#730]
When editing a file, the mature flag and copyright values are not repopulated on the edit page. If someone doesn't reselect them, they are reset to defaults. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@tiger5226 Can you help move this forward?

**Comment by tiger5226** [comment]
Yuppers!
