### ISSUE TITLE
undefined shown in embed / download URLs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#731]
Noticed this when editing files, but also seems to happen when a file is resolved recently. 

https://spee.ch/a/testdupes

![image](https://user-images.githubusercontent.com/8120721/48371825-cc2a4e00-e68a-11e8-9036-c50764fe63c6.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by skhameneh** [comment]
Re-opening, lbrynet fallback does not fix the `undefined` that is still returned for valid file content types.
This is a data mapping issue in the view components of the show page

**Comment by skhameneh** [comment]
It could also be in the reducers, I have not dug into this.

**Comment by jessopb** [comment]
Could you link an example? For content published before Jack added all the extra mime types to the daemon, file_name is pretty reliable to extract an extension from if all the other options come back null.  Chainquery does not have a file extension field, and the generated_extension creates it from content_type, which will be unreliable for legacy content (application/octet-stream). 

There's no place to map the data *from*, reliably, given what chainquery returns.

**Comment by tzarebczan** [comment]
This is now live on spee.ch prod.
