### ISSUE TITLE
incorrect resolution/redirection of URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#741]
spee.ch/LBRYCreditsAcceptedHere should redirect to  https://spee.ch/c/LBRYCreditsAcceptedHere

But instead it goes to an older abandoned claim: https://spee.ch/@3dprinting:5/lbrycreditsacceptedhere

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
Is this still a problem? Doesn't seem to be.

**Comment by tzarebczan** [comment]
Looks like it's working now, but wasn't last week. Maybe some caching issues or possibly data being refrrshed/corrected on chainquery. I'll close for now and keep an eye out to see if it happens again.

**Comment by tzarebczan** [comment]
This is now happening on: https://spee.ch/@AntiMedia:e/antimedia

Failed to resolve stream at lbry://antimedia#640c4d94f07f6aa3fab9f70a26314a03c494d139

It should be going to antimedia#8f51f4e412540567c4b3f07e419f0b8cc3386865

**Comment by tzarebczan** [comment]
Going to reopen again - it's happening now on spee.ch/six  - It's trying 3b0323054c9f1ae3a7bb9f80fdae2b5eb9bf5184, but it should be  6ec35f6a0cc5f0cc8b8401228b8ea1654667126b. Chainquery looks correct.
