### ISSUE TITLE
Dynamic Image Resizing

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#749]
Add support for URLs that dynamically scale or crop an image. As an example, the following URL would return a 200x200 cropped copy of the image, rather than the entire image.

`https://spee.ch/webapp-png-test-3.png?h=200&w=200&t=crop`

For whoever works on this ticket, I can share example code of how to figure out what part of an image to scale/crop based on the size and type.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by prkirby** [comment]
@kauffj is there any progress on this issue? I am finishing up LBRYPress now need to know if this is still the solution we plan to use for the multi-image issue. Thanks!

**Comment by Leopere** [comment]
Lots of additional server-side work to do in this use case.  Looks like a cool addition regardless.

**Comment by jessopb** [comment]
#60?
