### ISSUE TITLE
Unsupported content (in channels) breaks pagination

### ISSUE THREAD

**Issue by skhameneh** [lbryio/spee.ch#751]
An entire page of unsupported content in a channel will cause the channel to appear empty.

**Comment by jessopb** [comment]
ChannelAPI.js getChannelClaims takes a page number. Unsupported claims are included (application/octet-stream). Speech client gets a list of 12 claims from the server API. Solutions: rewrite to get more claims and sort, Implement an "unsupportd content type" default panel (maybw iwth a link to lbry-desktop), or SUPPORT the content type.
