### ISSUE TITLE
Internal deployment process needs clear documentation

### ISSUE THREAD

**Issue by jessopb** [lbryio/spee.ch#756]
Team members should have a central (notion) source of proper deployment and integration.

**Comment by alyssaoc** [comment]
@jessopb like this one? https://www.notion.so/lbry/How-To-Release-cfb38925465148e583ee8d2c35f8c44a
or if not this? what are you thinking? Notice the spee.ch section is empty (we need to up date it)

**Comment by alyssaoc** [comment]
closing for #811
