### ISSUE TITLE
Remove hardcoded Spee.ch filtering from shared chainquery queries

### ISSUE THREAD

**Issue by skhameneh** [lbryio/spee.ch#760]
Remove hardcoded content filtering from generic queries:
https://github.com/lbryio/spee.ch/issues/755
https://github.com/lbryio/spee.ch/issues/751

Method `getAllChannelClaims` in shared code should not have Spee.ch specific filtering hardcoded.

**Comment by jessopb** [comment]
#586 Will make this filtering obsolete.
