### ISSUE TITLE
Osprey CSS is not generated on release

### ISSUE THREAD

**Issue by skhameneh** [lbryio/spee.ch#763]
Osprey instance is missing the style customizations after deployments

**Comment by nikooo777** [comment]
`npm run build` should do that right? If so something isn't right because it's already performing that. I'll DM you on slack to make this quicker.

**Comment by skhameneh** [comment]
@nikooo777 the customization directory is missing, the copy doesn't do anything as a result.
I messaged you details (I don't have permissions to add an access key to the correct repo)
