### ISSUE TITLE
Retain details expansion on asset show page

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#800]
The last setting of whether the details on the show page are expanded or collapsed should persist across all requests. 

This may require solving the sub-problem of choosing how to persist data client-side across requests even for unauthenticated users.

**Comment by tzarebczan** [comment]
Ran into this often when editing files :)

**Comment by jessopb** [comment]
Moving collapsed to 'detailsExpanded' in redux state to persist within the session. Every browser session gets its own redux state.
To persist between sessions we can do something like this:
https://medium.com/@jrcreencia/persisting-redux-state-to-local-storage-f81eb0b90e7e

```
// localStorage.js
export const loadState = () => {
  try {
    const serializedState = localStorage.getItem('state');
    if (serializedState === null) {
      return undefined;
    }
    return JSON.parse(serializedState);
  } catch (err) {
    return undefined;
  }
}; 
```
```
// localStorage.js
export const saveState = (state) => {
  try {
    const serializedState = JSON.stringify(state);
    localStorage.setItem('state', serializedState);
  } catch {
    // ignore write errors
  }
};
```
```
// store.js
const persistedState = loadState();
const store = createStore(
  app,
  persistedState
);
store.subscribe(() => {
  saveState({
    todos: store.getState().todos
  });
});
```
```
// store.js
import throttle from 'lodash.throttle';
...
store.subscribe(throttle(() => {
  saveState({
    todos: store.getState().todos
  });
}, 1000));
```
