### ISSUE TITLE
spee.ch/channelname/name does not resolve

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#84]
Per a slack user, channel name followed by claim name does not resolve.  See below.

https://spee.ch/anarch/neko -doesn't work
https://spee.ch/neko - works
https://spee.ch/anarch/ccb0bf9f6705b2c9641d997e430c9f62430075e7 - works

Since the last example works, I think it should be able to resolve by name also.

**Comment by caseyparker** [comment]
It appears to be attempting to resolve "spee.ch/anarch#neko" for some reason. Shouldn't be hard to find.
