### ISSUE TITLE
master branch on dev2 works, while on staging does not

### ISSUE THREAD

**Issue by jessopb** [lbryio/spee.ch#861]
There is some difference between staging and dev2 (and a local arch linux environment pulled fresh from master) that causes at a large number of promises to break.
Consequently, the AssetBlocked page never shows on content that is supposed to be blocked.
factor | staging | dev2
node version | 8.12 | 8.11
ubuntu version| xenial | xenial
mysql | running | running

Staging is missing these three config keys: 
```
"closedRegistration": false,
    "serveOnlyApproved": false,
    "publishOnlyApproved": false,
```
Staging also has ': false' for its master password.

**Comment by jessopb** [comment]
staging has this error on npm ci: https://github.com/zkat/cipm/issues/58 
while dev2 does not - both hvae the same version of npm and libcipm

**Comment by skhameneh** [comment]
Things are building/running fine.  DMCA pages respond differently on staging environment (correctly blocks content but the page is not rendered with the full-page 451 as expected.

I still haven't found what's going on, I've rebuilt everything I can find.  `git clean -fxd`, rebuilt configs, `npm cache verify`, `npm i -g npm@latest`, etc.  Still investigating.  At least all environments "work" and prod runs as expected.

**Comment by skhameneh** [comment]
I'm going to de-prioritize this.  It's not impacting releases at the moment and I have spent more time on this than anticipated.

**Comment by skhameneh** [comment]
This is not a build issue, it's bad logic in the app, closing and will open a more specific issue.
