### ISSUE TITLE
Move media type strings to constants and use a content type lookup util

### ISSUE THREAD

**Issue by jessopb** [lbryio/spee.ch#882]
The code is littered with tests for 'image/gif', or determinetype() or extension for 'type/ext'. 
Adding a new type support involves editing many files consistently.
This should be centralized.

- [ ] Dev can add a file type to publish capabilities by adding a content type to centralized location
- [ ] Dev can add a file type to preview or show by adding a content type to centralized location
- [ ] Dev can choose a viewer by category: IMAGE, TEXT, DOCUMENT, 3D, VIDEO.
- [x] Admin can enable or disable types in config
- [x] Admin can set file size limits with variable granularity.
 - Do we need variable limits for "image" (gif different from jpg)?

**Comment by kauffj** [comment]
I endorse cleaning this up on the path to filtering and/or as you're adding support for more types. 

It seems decently likely that we'll want a file to carry around both it's media type and a higher-level category (like "image", "text" as you say).

If we need content-specific file size limit, I'd guess that category-based would be sufficient. However, if this adds any substantial complexity, I think a single global limit is fine.
