### ISSUE TITLE
Check if Sequelize has been patched for new MySQL/MariaDB versions

### ISSUE THREAD

**Issue by skhameneh** [lbryio/spee.ch#885]
The last time we checked to update MySQL (or move to MariaDB), Sequelize didn't support the new auth handshakes.

See if we can upgrade Sequelize and DB's.

**Comment by skhameneh** [comment]
Unclear if this is resolved, see:
https://github.com/sequelize/sequelize/issues/10189
https://github.com/sidorares/node-mysql2/issues/744

**Comment by DaveStein** [comment]
Just ran into this issue.
