### ISSUE TITLE
Update SDK calls for 0.30.5+, apis changed/old ones removed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/spee.ch#892]
See https://github.com/lbryio/lbry/releases/tag/v0.30.5 for list of api calls that were removed. The wallet ones are replaced by ```account```

This affects anyone running the setup process because it pulls the latest daemon release.

**Comment by tzarebczan** [comment]
Also, see desktop side issue for other breaking changes with 0.31.0 : https://github.com/lbryio/lbry-desktop/issues/2231 or https://github.com/lbryio/lbry/releases/tag/v0.31.0

**Comment by jessopb** [comment]
source and sdhash were removed from the relevant calls
wallet_ methods were replaced with account or address
download_dir has replaced download_directory
readme has been updated to direct the new use of lbrynet command line
