### ISSUE TITLE
investigate why spee.ch links don't unfurl on twitter

### ISSUE THREAD

**Issue by billbitt** [lbryio/spee.ch#94]
story: as a user, when I share a spee.ch link on twitter I want twitter to load the image from the link so that my followers can see the image without having to click through the link.

issue: At the moment, twitter does not retrieve the asset and display it in your tweet, it just shows the link.

steps to reproduce (from @finer9 ) in twitter 
1. click image icon in new tweet box 
2. in file chooser dialog box paste https://spee.ch/url.jpg here 
3. It fetches the location and uploads it almost like a local image

**Comment by billbitt** [comment]
Potential solutions include adding the file extension to the spee.ch url

**Comment by filipnyquist** [comment]
I think this might be caused by the time while fetching the request or not sending the correct metadata

**Comment by billbitt** [comment]
-  I'm issuing a PR to add twitter Summary Card support for 'show' actions for images.
-  support for 'serve' actions will require a more invasive update in order to send html when twitter is trying to unfurl.
-  support for unfurling gifs and videos will require applying to be white listed via twitter for Player Cards
