### ISSUE TITLE
app does not tell you your channel is not ready for published claims

### ISSUE THREAD

**Issue by jessopb** [lbryio/spee.ch#982]
Currently, You can create a channel and attempt to publish a claim in that channel, but it fails.
Dropzone or other publish tools should notify you that publishing is disabled until channel is confirmed.

Later publishes can be put into a queue.

**Comment by tzarebczan** [comment]
The channel doesn't need to be confirmed, but it does take a couple seconds (in my experience up to 3/5) to be able to publish after creation. I wonder if this can be improved with a --blocking flag on more calls... @eukreign? 

See also https://github.com/lbryio/lbry/issues/1394
