### ISSUE TITLE
Support 0.37 LBRY SDK changes

### ISSUE THREAD

**Issue by kauffj** [lbryio/spee.ch#988]
This issue should potentially be closed and split into several issues. The issues are:

- Support new tags for both publishing and file show
- Support new height/width/duration metadata fields (or does SDK do everything important here?)
- Support new channel creation fields and display them on channels
- Support release data based sorting on channel show pages
- Support new range requests streaming
- Update old claims

**Comment by kauffj** [comment]
This ticket should be reduced in scope to be the barebones changes to get the new SDK running.

**Comment by tzarebczan** [comment]
Barebones changes are pushed. Will create separate issues for the other features if they don't exist.
